### ISSUE TITLE
Set up staging environment for lookup.ld4l.org

### ISSUE THREAD

**Issue by zimeon** [LD4P/qa_server#11]
Given troubles with #3 and redeployment of the main service, we should have a staging environment to avoid such issues in the future

**Comment by zimeon** [comment]
Ref: https://culibrary.atlassian.net/browse/DLITSYS-3002

**Comment by zimeon** [comment]
Have closed DLITSYS-3002 as Greg has set up process for deploying staging instance as we do future updates. Done.

**Comment by zimeon** [comment]
This is blocked as we haven't worked out with Greg how to get this going

**Comment by elrayle** [comment]
See next steps in https://github.com/cul-it/qa_server/issues/39
