### ISSUE TITLE
Implement LDPath for SVDE in DAVE and QA

### ISSUE THREAD

**Issue by sfolsom** [LD4P/qa_server#115]
For lookups with context for SVDE, implement related LDPath in DAVE and QA: https://docs.google.com/spreadsheets/d/1rPvEoP9iYNkxJ0eWC8gXe3ci7e6mhW0da59xkGhadi0/edit#gid=502967565

**Comment by elrayle** [comment]
Initially addressed for the first 5 Share-VDE institutional configs in PR https://github.com/cul-it/qa_server/pull/93.  

To see all related PRs, use this search... https://github.com/cul-it/qa_server/pulls?utf8=%E2%9C%93&q=is%3Apr+is%3Aclosed+sharevde

Closing... completed for all share-vde auths.
