### ISSUE TITLE
Implement LDPath for LCSH in DAVE and QA

### ISSUE THREAD

**Issue by sfolsom** [LD4P/qa_server#116]
For lookups with context for LCSH, implement related LDPath in DAVE and QA: https://docs.google.com/spreadsheets/d/1rPvEoP9iYNkxJ0eWC8gXe3ci7e6mhW0da59xkGhadi0/edit#gid=221282005

**Comment by elrayle** [comment]
### ACTION

- [ ] SPARQL query in cache updated to return context
- [ ] Configured in QA
- [ ] Running test queries in QA correctly extract out the extended context (Issue #142)

### Context:

* Preferred label = skos:prefLabel
* Alternative Label = skos:altLabel
* Type = rdf:type
* Broader = skos:broader / skos:prefLabel
* Narrower = skos:narrower / skos:prefLabel
* Citation note = madsrdf:hasSource / madsrdf:citation-note
* Citation source = madsrdf:hasSource / madsrdf:citation-source
* Citation status = madsrdf:hasSource / madsrdf:citation-status

### Related Work

* Issue #141 Remove subauthorities for locsubjects_ld4l_cache
* Issue #142 Identify queries for LCSH that include results with the extended context

**Comment by elrayle** [comment]
### Remaining Issues

Data coming back from cache is missing.
* Broader and Narrower do not have triples for their IDs nor labels
* madsrdf:hasSource triple exists with a blank node for the <object>, but the blank node does not have any predicates for madsrdf:citation-note, madsrdf:citation-source, madsrdf:citation-status

**Comment by elrayle** [comment]
@eichmann There are two action items in the last comment.  The first requires changes to the way the cache returns data.  It is labeled `Data coming back from cache is missing`.  The other action item is mine.
