### ISSUE TITLE
Implement LDPath for MESH in DAVE and QA

### ISSUE THREAD

**Issue by sfolsom** [LD4P/qa_server#117]
For lookups with context for MESH, implement related LDPath in DAVE and QA: https://docs.google.com/spreadsheets/d/1rPvEoP9iYNkxJ0eWC8gXe3ci7e6mhW0da59xkGhadi0/edit#gid=2113261477

**Comment by elrayle** [comment]
Closing.  This was done in production in PR https://github.com/cul-it/qa_server/pull/203 and synced here in PR #335.
