### ISSUE TITLE
Implement LDPath for LCGFT in DAVE and QA

### ISSUE THREAD

**Issue by sfolsom** [LD4P/qa_server#118]
For lookups with context for LCGFT, implement related LDPath in DAVE and QA: https://docs.google.com/spreadsheets/d/1rPvEoP9iYNkxJ0eWC8gXe3ci7e6mhW0da59xkGhadi0/edit#gid=696491968

**Comment by elrayle** [comment]
Closing:  The configuration for QA is complete in PR https://github.com/cul-it/qa_server/pull/90.  Issues for caching are described in Issue #50.
