### ISSUE TITLE
Implement LDPath for Getty ULAN in DAVE and QA

### ISSUE THREAD

**Issue by sfolsom** [LD4P/qa_server#119]
For lookups with context for ULAN, implement related LDPath in DAVE and QA https://docs.google.com/spreadsheets/d/1rPvEoP9iYNkxJ0eWC8gXe3ci7e6mhW0da59xkGhadi0/edit#gid=0

**Comment by elrayle** [comment]
Subauths:

* person
  - [ ] profile editor: GETTY_ULAN person (QA)
  - [ ] sinopia editor: GETTY_ULAN person (QA)
  - [ ] qa config: person
  - [ ] cache entity: Person
* organization
  - [ ] profile editor: GETTY_ULAN organization (QA)
  - [ ] sinopia editor: GETTY_ULAN organization (QA)
  - [ ] qa config: organization
  - [ ] cache entity: Organization
* place
  - [ ] profile editor: GETTY_ULAN place (QA)
  - [ ] sinopia editor: GETTY_ULAN place (QA)
  - [ ] qa config: place
  - [ ] cache entity: Place

Extended Context:

Configure extended context according to spreadsheet (link in original description):

- [ ] cache returns extended context
- [ ] qa configured to return extended context

**Comment by sfolsom** [comment]
The context for ULAN as it currently is set up in the spreadsheet requires being able to query a combination of ULAN (for agents) and AAT (for agent types, etc.) and TGN for birthplaces, deathplaces, etc.

**Comment by sfolsom** [comment]
Re: possible blank nodes for dates, here is what I'm seeing in the triplestor (no blank nodes)

<http://vocab.getty.edu/ulan/bio/4000111060>
        a                   <http://vocab.getty.edu/ontology#Biography> ;
        <http://purl.org/dc/terms/contributor>
                <http://vocab.getty.edu/ulan/contrib/2500000005> ;
        schema:description  "Canadian artist, born 1935" ;
        schema:gender       <http://vocab.getty.edu/aat/300189559> ;
        <http://vocab.getty.edu/ontology#estEnd>
                "2035"^^<http://www.w3.org/2001/XMLSchema#gYear> ;
        <http://vocab.getty.edu/ontology#estStart>
                "1935"^^<http://www.w3.org/2001/XMLSchema#gYear> .

**Comment by sfolsom** [comment]
Nearly all of the requested context has been implemented. The little remaining context that isn't implemented requires querying across multiple Getty Vocabs, which would require major changes to the ingest/indexing process. We're going to close this issue for now.
