### ISSUE TITLE
Implement LDPath for Getty TGN in DAVE and QA

### ISSUE THREAD

**Issue by sfolsom** [LD4P/qa_server#121]
For lookups with context for Getty TGN, implement related LDPath in DAVE and QA: 
 https://docs.google.com/spreadsheets/d/1rPvEoP9iYNkxJ0eWC8gXe3ci7e6mhW0da59xkGhadi0/edit#gid=611820102

**Comment by sfolsom** [comment]
Looks like this a problem with how Sinopia is reading urn:ld4p:qa:gettytgn fromhttps://github.com/LD4P/sinopia_editor/blob/944fa55f4e7c03f5bf6f078824f9fa741fdbd1c7/static/lookupConfig.json#L378. It's pointing instead to the AAT QA lookup. cc: @jermnelson

**Comment by elrayle** [comment]
There were also several ulan configs pointing to aat.  I fixed the tgn one and the ulan configs in PR https://github.com/LD4P/sinopia_editor/pull/1391

**Comment by elrayle** [comment]
Looks like getty tgn has 1 part of the extended context defined, but not all requested extended context.  According to the spread sheet, the extended context should be...

- [ ] Preferred label = ^foaf:focus / xl:prefLabel / xl:literalForm
- [ ] Variant label = ^foaf:focus / xl:altLabel / xl:literalForm
- [x] Parent body = ^foaf:focus / gvp:parentString
- [ ] Place type = ^focus / gvp:placeTypePreferred
- [ ] Broader = ^foaf:focus / gvp:broaderPreferred / xl:altLabel / xl:literalForm

**Comment by sfolsom** [comment]
Based on conversations with Dave on 10/29-10/30, I've updated the TGN spreadsheet to include better search and display for broader locations. E.g. Boulder, CO or Paris, France.

**Comment by sfolsom** [comment]
The context for TGN matches the spreadsheet now. We can close this issue, but first I want to ask (I think the answer is *no*) can the LDPath/SPARQL queries go across vocabularies? TGN places link to AAT types, e.g. 

"property": "Place type",
        "values": [
          "http://vocab.getty.edu/aat/300008347"

Ideally, we could get the label from AAT for the type displayed in the TGN lookup, but this isn't a deal breaker.

**Comment by sfolsom** [comment]
Nearly all of the requested context has been implemented. The little remaining context that isn't implemented requires querying across multiple Getty Vocabs, which would require major changes to the ingest/indexing process. We're going to close this issue for now.
