### ISSUE TITLE
loc_names_rwo_ld4l_cache - blanknodes that are for different entities share the same blanknode identifier

### ISSUE THREAD

**Issue by elrayle** [LD4P/qa_server#125]
In the results of…
```
curl -L -D - -H 'Accept: application/n-triples' 'http://services.ld4l.org/ld4l_services/loc_name_batch.jsp?query=mark%20twain&maxRecords=4&entity=Person&lang=en'
```

has the following triples…
```
<http://id.loc.gov/authorities/names/n82045653> <http://www.loc.gov/mads/rdf/v1#adminMetadata> _:b0 .
<http://id.loc.gov/authorities/names/n2017045245> <http://www.loc.gov/mads/rdf/v1#hasVariant> _:b0 .
<http://id.loc.gov/authorities/names/n89103996> <http://www.loc.gov/mads/rdf/v1#hasVariant> _:b0 .
<http://id.loc.gov/rwo/agents/n79021164> <http://www.loc.gov/mads/rdf/v1#deathDate> _:b0 .
```

The symptom I’m seeing is the variant label for n89103996 is showing up in the list for n2017045245.

CAUSE: blanknode numbering is being reused across entities.  Each entity starts counting over again at 0.

I marked this as Infrastructure because I believe it applies to all authorities that have extended context.

**Comment by eichmann** [comment]
It appears that Jena tidies the blank node IDs as it returns them.  The tag library currently generates a new model for each entity.  I _think_ that I can check for an existing model and then merge the new results which _should_ finesse our problem.  This will take some testing though...

**Comment by eichmann** [comment]
Fix for al CONSTRUCT-using interfaces deployed yesterday to wintermute for testing by @elrayle

**Comment by elrayle** [comment]
Closing:  Fixed per @eichmann
