### ISSUE TITLE
Lookups generally shouldn't be case sensitive

### ISSUE THREAD

**Issue by sfolsom** [LD4P/qa_server#133]
For tracking purposes, please create a separate issue for each indexing improvement request.

- [X] Please describe the expected performance and accuracy of a particular vocabulary. LOC all genres gets different results depending on whether you type "Maps " or "maps " (both with a space. 
- [X] If applicable, please update and provide links related to existing tests, e.g. https://github.com/LD4P/qa_server/pull/132

**Comment by elrayle** [comment]
## Example

authority: LCDGT
search query: 'dancers' vs. 'Dancers'
loc id: dg2015060747
prefLabel: 'Dancers'
loc rwo uri: http://id.loc.gov/authorities/demographicTerms/dg2015060747

When performing these two queries, 'Dancers' is an exact match for dg2015060747.  'dancers' is not an exact match.

**Comment by sfolsom** [comment]
Another example where capitalization is throwing results:

https://lookup.ld4l.org/authorities/search/linked_data/locnames_ld4l_cache?q=university%20of%20pennsylvania&maxRecords=4&context=true

https://lookup.ld4l.org/authorities/search/linked_data/locnames_ld4l_cache?q=University%20of%20Pennsylvania&maxRecords=4&context=true

**Comment by elrayle** [comment]
And another...

Authority: locsubjects_ld4l_cache
Query: 'history' vs. 'History'

When performing these queries, 'history' returns results in 7s.  

'History' returns an error...

```
curl -L -D - -H 'Accept: application/n-triples' 'http://services.ld4l.org/ld4l_services/loc_subject_batch.jsp?query=History&maxRecords=8&startRecord=1&lang=en'
date
HTTP/1.1 502 Proxy Error
Date: Fri, 27 Mar 2020 15:47:50 GMT
Server: Apache/2.4.33 (Unix) PHP/7.1.16 LibreSSL/2.2.7
Content-Length: 449
Content-Type: text/html; charset=iso-8859-1

<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>502 Proxy Error</title>
</head><body>
<h1>Proxy Error</h1>
<p>The proxy server received an invalid
response from an upstream server.<br />
The proxy server could not handle the request <em><a href="/ld4l_services/loc_subject_batch.jsp">GET&nbsp;/ld4l_services/loc_subject_batch.jsp</a></em>.<p>
Reason: <strong>Error reading from remote server</strong></p></p>
</body></html>
```

**Comment by elrayle** [comment]
Need to add accuracy tests for the described scenarios.

**Comment by sfolsom** [comment]
Tests for capitalization: https://github.com/LD4P/qa_server/pull/367, https://github.com/LD4P/qa_server/pull/368, https://github.com/LD4P/qa_server/pull/369

**Comment by elrayle** [comment]
Proposed adjustment:
* if an exact match including case, this will be rank 1
* if there is an exact match ignoring case, this will be rank 1 if no case match or rank 2 if there is a case match

@eichmann will update logic in search API

**Comment by eichmann** [comment]
A full reindexing of all caches is complete with an additional field, the lower cased label. The Lucene search logic now check this as the second step (after true (case-sensitive) exact match).

**Comment by eichmann** [comment]
I believe this is now resolved.

**Comment by elrayle** [comment]
Verified fixed.
