### ISSUE TITLE
Type ahead support for incomplete words

### ISSUE THREAD

**Issue by sfolsom** [LD4P/qa_server#134]
For tracking purposes, please create a separate issue for each indexing improvement request.

- [X] Please describe the expected performance and accuracy of a particular vocabulary. Would expect type ahead to work with incomplete words, e.g. "vonnegu" would provide any number of "Vonnegut" from LCNAF
- [ ] If applicable, please update and provide links related to existing tests. Not sure how to write a test for this, given that there may be 100's of "Vonneguts"

**Comment by elrayle** [comment]
Need to add accuracy tests for the described scenario.

**Comment by sfolsom** [comment]
@elrayle @eichmann I'm not sure how to write a test for something like "Vonnegu" where the cataloger using a type ahead would see _some_ values that complete the string to "Vonnegut". Honestly, I don't remember where this example came from, and unless you think differently it might be worth tabling this one.

**Comment by elrayle** [comment]
This and several other similar issues related to ordering of results or the approach to performing the search are marked as low priority.  This issue is being closed as `wontfix`, but can be reopened if it becomes a priority.

See also: 
* Issue #203
* Issue #190
