### ISSUE TITLE
Remove subauthorities for locsubjects_ld4l_cache

### ISSUE THREAD

**Issue by elrayle** [LD4P/qa_server#141]
### Description

Make sure that the subauthorities are consistent with the information in the [LCSH tab](https://docs.google.com/spreadsheets/d/1rPvEoP9iYNkxJ0eWC8gXe3ci7e6mhW0da59xkGhadi0/edit#gid=221282005) of the Indexing of External Data for Look-ups spreadsheet.

The spreadsheet has one EntityType = skos:Concept.  Subauthorities are commonly broken on entity type.

I interpret the spreadsheet to mean that there should be no subauthorities for LCSH.

### Expected configuration

```
    "subauthorities": { }
```

### Actual configuration

Current QA has configured...
```
    "subauthorities": {
      "person":         "Person",
      "organization":   "Organization",
      "place":          "Place",
      "intangible":     "Intangible",
      "geocoordinates": "GeoCoordinates",
      "work":           "Work"
    }
```

### ACTION

Remove the subauthorities section of the configuration for locsubjects_ld4l_cache.

### Related Work

* Issue #116 Implement LDPath for LCSH in DAVE and QA

**Comment by sfolsom** [comment]
For it would be nice to have the subauthorities removed. I'm hoping for more direction from catalogers on whether sub-authorities would be useful and I need to confirm the madsrdf:DeprecatedAuthority pattern in LCSH. Both may lead to changes in the request.

**Comment by elrayle** [comment]
@sfolsom If you decide to add deprecated/active as subauthorities, please open a new issue.
