### ISSUE TITLE
Add CERL to lookups

### ISSUE THREAD

**Issue by lindaisaac** [LD4P/qa_server#144]
Please add CERL Thesaurus to lookups - https://data.cerl.org/thesaurus/_search.
Added information to the spreadsheet.

~~~~~~~~~

_Please only use this issue template for LD4P2 requests for a new data source to be added to QA. If your requesting changes to how a dataset currently available in QA is treated, please use the indexing bug issue template._

__For LD4P2 partners and cohorts:__


Please perform each task listed below. (Email sf433 @ cornell dot edu with questions):
- [ ] Please consult the LD4P2 QA Authority Support Plan (https://github.com/LD4P/qa_server/wiki/Authority-Lookup-Support-Plan-for-Sinopia) to confirm the dataset isn't already being supported.
- [ ] Identify the data source: (Include the Data Source Name, its homepage URL, and any relevant API and/or download information to aid in caching.)
- [ ] QA has the ability to provide contextual information about an entity during the look-up experience. In order to do so, decisions need to be made about how to index the RDF descriptions of entities in the dataset. Add a new tab and indexing information for the data source to the following spreadsheet: https://docs.google.com/spreadsheets/d/1rPvEoP9iYNkxJ0eWC8gXe3ci7e6mhW0da59xkGhadi0/edit?usp=sharing.  (See the existing LCNAF tab in the spreadsheet as an example)



Next steps: 

Once the above actions have taken place, a link to a YAML file will be shared with the requestor via a comment in the issue in order to complete Accuracy Test, https://github.com/LD4P/qa_server/wiki/Writing-Tests-for-an-Authority#accuracy-test. Edit directly the YAML file in Github, save. Create a Pull Request to be reviewed. Be sure to including a meaningful commit message (e.g. adding accuracy tests for Authority X). 

Context on Accuracy Tests: In order to make sure the QA search behavior (recall and relevancy) are meeting expectations, QA uses YAML to define test parameters. These parameters include the ability to declare for a particular text string searched, the results should include a particular resource (identified by a URI) and what is the maximum position in the results the resource should be found.)


_Please note, all requests for new data sources in QA will be prioritized by the LD4P2 project. Due to time restrictions there is no guarantee that all requests will be added to QA during the lifetime of the LD4P2 grant; regardless of resources it is still useful to know which datasets the community would find useful in such a lookup service._

**Comment by sfolsom** [comment]
@elrayle currently CERL doesn't seem to provide dumps. Using https://www.cerl.org/resources/cerl_thesaurus/sru is this candidate for direct access for now, until dumps might be provided?

**Comment by eslao** [comment]
@elrayle @sfolsom We have just now been provided with a json-ld dump here: https://owncloud.gwdg.de/index.php/s/hvkrWqplJAMyp96

Is this helpful?

**Comment by eichmann** [comment]
@eslao @sfolsom CERL triplestore now available for SPARQLing at http://services.ld4l.org/fuseki/dataset.html?tab=query&ds=/CERL after much fiddling.  I had to write a custom loader due to the NDJSON formatting and the ISO-8859-1 character set.

**Comment by eslao** [comment]
Indexing and context specified here: https://docs.google.com/spreadsheets/d/1rPvEoP9iYNkxJ0eWC8gXe3ci7e6mhW0da59xkGhadi0/edit#gid=911870085 (see questions under "use case" column)

Users will need to perform lookups against four subauthorities: 
- persons (http://rdvocab.info/uri/schema/FRBRentitiesRDA/Person)
- imprints (ct:ImprintName)
- corporate bodies (http://rdvocab.info/uri/schema/FRBRentitiesRDA/CorporateBody)
- persons, imprints, and corporate bodies combined

Added a test file here: https://github.com/LD4P/qa_server/blob/master/lib/generators/qa_server/templates/config/authorities/linked_data/scenarios/cerl_ld4_cache_validation.yml

**Comment by eslao** [comment]
Any updates on the status of this lookup? Questions about context spec? Thanks!

**Comment by elrayle** [comment]
@eslao I touched base with @eichmann this morning on CERL and a few other issues.  Barring unexpected snags, he is expecting to have CERL deployed by the end of the week.

**Comment by elrayle** [comment]
Closing... CERL is on production
