### ISSUE TITLE
MARC Presentation Format List (id.loc.gov)

### ISSUE THREAD

**Issue by gracianipicardo** [LD4P/qa_server#148]
_Please only use this issue template for LD4P2 requests for a new data source to be added to QA. If your requesting changes to how a dataset currently available in QA is treated, please use the indexing bug issue template._

__For LD4P2 partners and cohorts:__

Please perform each task listed below. (Email sf433 @ cornell dot edu with questions):
- [x] Please consult the LD4P2 QA Authority Support Plan (https://github.com/LD4P/qa_server/wiki/Authority-Lookup-Support-Plan-for-Sinopia) to confirm the dataset isn't already being supported.

- [x] Identify the data source: (Include the Data Source Name, its homepage URL, and any relevant API and/or download information to aid in caching.)

**MARC Presentation Format List: http://id.loc.gov/vocabulary/mpresformat

- [ ] QA has the ability to provide contextual information about an entity during the look-up experience. In order to do so, decisions need to be made about how to index the RDF descriptions of entities in the dataset. Add a new tab and indexing information for the data source to the following spreadsheet: https://docs.google.com/spreadsheets/d/1rPvEoP9iYNkxJ0eWC8gXe3ci7e6mhW0da59xkGhadi0/edit?usp=sharing.  (See the existing LCNAF tab in the spreadsheet as an example)

**Based on the pattern of how similar vocabularies published in id.loc.gov are being accessed from Sinopia, this vocabulary should probably be a controlled list.

Next steps: 

Once the above actions have taken place, a link to a YAML file will be shared with the requestor via a comment in the issue in order to complete Accuracy Test, https://github.com/LD4P/qa_server/wiki/Writing-Tests-for-an-Authority#accuracy-test. Edit directly the YAML file in Github, save. Create a Pull Request to be reviewed. Be sure to including a meaningful commit message (e.g. adding accuracy tests for Authority X). 

Context on Accuracy Tests: In order to make sure the QA search behavior (recall and relevancy) are meeting expectations, QA uses YAML to define test parameters. These parameters include the ability to declare for a particular text string searched, the results should include a particular resource (identified by a URI) and what is the maximum position in the results the resource should be found.)

_Please note, all requests for new data sources in QA will be prioritized by the LD4P2 project. Due to time restrictions there is no guarantee that all requests will be added to QA during the lifetime of the LD4P2 grant; regardless of resources it is still useful to know which datasets the community would find useful in such a lookup service._

**Comment by elrayle** [comment]
@gracianipicardo I'm not seeing this on LOC's linked data download page (http://id.loc.gov/download/).  Do you know if this vocabulary is available as linked data?

**Comment by gracianipicardo** [comment]
@elrayle http://id.loc.gov/vocabulary/mpresformat.html. I am guessing all the other vocs I have requested won't be on the download page, but available on the vocabulary page in id.loc.gov.

**Comment by sfolsom** [comment]
This was addressed in a Sinopia pull request last week (https://github.com/LD4P/sinopia_editor/pull/1294). It should be available for profiles now to lookup as typeahead list.
