### ISSUE TITLE
Searching variants in LCSH

### ISSUE THREAD

**Issue by sfolsom** [LD4P/qa_server#155]
For tracking purposes, please create a separate issue for each indexing improvement request.

- [X] Please describe the expected performance and accuracy of a particular vocabulary.
See Issue name.
- [X] If applicable, please update and provide links related to existing tests, e.g. https://github.com/LD4P/qa_server/tree/master/lib/generators/qa_server/templates/config/authorities/linked_data/scenarios

https://github.com/LD4P/qa_server/pull/154

- [ ] If applicable, please update the relevant tab in https://docs.google.com/spreadsheets/d/1rPvEoP9iYNkxJ0eWC8gXe3ci7e6mhW0da59xkGhadi0/edit?usp=sharing for the particular dataset in question

**Comment by elrayle** [comment]
@sfolsom I am not understanding what action you are requesting in this issue.

**Comment by sfolsom** [comment]
Looks like since July the variant labels have been indexed well enough that the test in the pull request https://github.com/LD4P/qa_server/pull/154 now passes. I think we can close this.
