### ISSUE TITLE
Request authority Discogs be supported

### ISSUE THREAD

**Issue by elrayle** [LD4P/qa_server#17]
**Datasource:**  [Discogs](https://www.discogs.com/)

**Request:** Consider connecting to Cornell's Rails app which extended QA to access Discogs and convert to linked data into the QaServer system.  May want to consider caching converted data in services.ld4l.org.

**Expected Workflow:**

* Goto Sinopia Workspace
* Click Load Discogs tab
* Search for record in Discogs using QaServer
* Select a Discogs record
* Use QaServer term fetch for the selected record to get all available data
* A new Sinopia record is created and pre-populated with Discogs data
* Approve copied data, add new data, modify data...  and Save

**Comment by zimeon** [comment]
Most of this will be handled by Tim's work to build in support for import from Discogs into QA

**Comment by tworrall** [comment]
@elrayle Is this issue superceded by [Issue 35](https://github.com/LD4P/qa_server/issues/35)? I think you created this one before the decision to make the Discogs authority part of QA and not the QA Server.

**Comment by zimeon** [comment]
Closing this for now. It has a first stab at workflow but isn't quite how we are moving forward now.
