### ISSUE TITLE
Explore caching Sinopia data for search/copy

### ISSUE THREAD

**Issue by elrayle** [LD4P/qa_server#18]
**Datasource:**  Sinopia Bibframe Data

**Request:** Consider caching Sinopia Bibframe data in services.ld4l.org to allow for search and copy of the data into new Sinopia Bibframe data records.  

**Exploration:** Need to determine if it is possible in the current architecture, whether or not the system will scale appropriately, and how the cache will be refreshed.

**Expected Workflow:**

* Goto Sinopia Workspace
* Click Load Sinopia data tab
* Search for Bibframe data in Sinopia using QaServer
* Select a Sinopia Bibframe data record
* Use QaServer term fetch for the selected record to get all available data
* A new Sinopia Bibframe record is created and pre-populated with selected Bibframe data
* Approve copied data, add new data, modify data...  and Save

**Comment by elrayle** [comment]
@dave Do you want to comment on any of this?  I don't see this as a top priority at this point in time, but wanted to put it out there as food for thought.

**Comment by jermnelson** [comment]
I'm not sure what adding this additional caching round-trip to the QA adds to our already working fast Elasticsearch index and direct download of RDF with LDP calls to Trellis for Sinopia managed resources.

**Comment by elrayle** [comment]
The decision was made not to cache Sinopia data in the QA cache system.  Closing this issue.
