### ISSUE TITLE
LCMPT does not include Citation note, source, or status in search results

### ISSUE THREAD

**Issue by elrayle** [LD4P/qa_server#183]
authority: LCMPT
search query: band
loc id: mp2013015048
loc rwo uri: <http://id.loc.gov/authorities/performanceMediums/mp2013015048>

id.loc.gov has these triples related to Citation note, source, status...

```
<http://id.loc.gov/authorities/performanceMediums/mp2013015048> <madsrdf:hasSource> _:bnode129 .
_:bnode129 <madsrdf:citation-source> "Wikipedia, October 21, 2013" . 
_:bnode129 <madsrdf:citation-note> "(under Concert band: also called wind band, symphonic band, symphonic winds, wind orchestra, wind symphony, wind ensemble, symphonic wind ensemble)"@en . 
_:bnode129 <madsrdf:citation-note> "found" .
```

curl -L -D - -H 'Accept: application/n-triples' 'http://services.ld4l.org/ld4l_services/loc_performance_batch.jsp?query=band&maxRecords=1&startRecord=1&lang=en'

The results returned from the cache has the following triples related to Citation source and note...

```
<http://id.loc.gov/authorities/performanceMediums/mp2013015048> <madsrdf:hasSource> _:b2 .
```

Missing triple...

```
_:b2 <madsrdf:citation-source> "Wikipedia, October 21, 2013" . 
_:b2 <madsrdf:citation-note> "(under Concert band: also called wind band, symphonic band, symphonic winds, wind orchestra, wind symphony, wind ensemble, symphonic wind ensemble)"@en . 
_:b2 <madsrdf:citation-note> "found" .
```

### Related Issues

#184 LCMPT does not labels for broader and narrower
#13 Request authority LCMPT be supported

**Comment by eichmann** [comment]
@elrayle fix deployed and ready for validation.

**Comment by elrayle** [comment]
Closing: Verified citation data are in search results.
