### ISSUE TITLE
LCSH does not include Citation note, source, or status in search results

### ISSUE THREAD

**Issue by elrayle** [LD4P/qa_server#185]
authority: LCSH
search query: Boroughs (Municipal subdivision)
loc id: sh85015885
loc rwo uri: <http://id.loc.gov/authorities/subjects/sh85015885>

id.loc.gov has these triples related to Citation note, source, status...

```
<http://id.loc.gov/authorities/subjects/sh85015885> <madsrdf:hasSource> _:bnode129 .
_:bnode73 <madsrdf:citation-source> "Wikipedia, Feb. 17, 2013" . 
_:bnode73 <madsrdf:citation-note> "(A borough is an administrative division in various countries.  ...)"@en . 
_:bnode73 <madsrdf:citation-note> "found" .
```

curl -L -D - -H 'Accept: application/n-triples' 'http://services.ld4l.org/ld4l_services/loc_performance_batch.jsp?query=band&maxRecords=1&startRecord=1&lang=en'

The results returned from the cache has the following triples related to Citation source and note...

```
<http://id.loc.gov/authorities/subjects/sh85015885> <madsrdf:hasSource> _:b2 .
```

Missing triple...

```
_:b2 <madsrdf:citation-source> "Wikipedia, Feb. 17, 2013" . 
_:b2 <madsrdf:citation-note> "(A borough is an administrative division in various countries.  ...)"@en . 
_:b2 <madsrdf:citation-note> "found" .
```

### Related Issues

#186 LCSH does not labels for broader and narrower
#116 Implement LDPath for LCSH in DAVE and QA

**Comment by eichmann** [comment]
@elrayle fix deployed and ready for validation.

**Comment by elrayle** [comment]
Closing: Verified citation data are in search results.
