### ISSUE TITLE
Create swagger API documentation for qa_server

### ISSUE THREAD

**Issue by elrayle** [LD4P/qa_server#19]
Request from:  @cmh2166 

Request:  Document and version access API
   • QUERY: `http://localhost:3000/qa/search/linked_data/:authname/(:subauthname)?:params`
   • FETCH: `http://localhost:3000/qa/show/linked_data/:authname/:uri_or_id`

Example to follow...
* https://github.com/folio-org/okapi/blob/master/okapi-core/src/main/raml/okapi.raml

Other resources and examples...
* https://swagger.io/docs/specification/about/
* https://raml.org/

**Comment by zimeon** [comment]
With regard to versioning, should we be adding a version to the path: e.g. `http://localhost:3000/qa/1.1/search/linked_data/:authname/(:subauthname)?:params`
so that multiple API versions can be supported at the same time to decouple upgrades of clients and servers?

**Comment by elrayle** [comment]
API versioning determines...
* access API (e.g. GET show, GET search, etc.)
* results format
* configuration file format

To support multiple versions at a time would require that the code be able to read in multiple configuration file formats AND be able to produce results in multiple formats.  Although this is a good aspiration, it may prove challenging with limited resources.

**Comment by zimeon** [comment]
Discussion from Friday was that if we want to version the API it might be best/simplest to have multiple versions of the entire application running and version in the DNS name, e.g.:
 
  * `http://lookup.ld4l.org/qa/....` -- always current/latest version
  * `http://v1.lookup.ld4l.org/qa/....` -- some specific version (e.g. `v1` in this case)

**Comment by zimeon** [comment]
I think this issue is split into two: documentation and versioning seem rather different issues

**Comment by elrayle** [comment]
The Swagger API doc is part of QA 2.1.2 release.  Cul-it/qa_server master branch makes use of this release.  As soon as the deployment issues are resolved, this will be available.

There is documentation of the process to use the API and what it returns in the QA README.  

Query: https://github.com/samvera/questioning_authority/tree/min_context#query
Term: https://github.com/samvera/questioning_authority/tree/min_context#find-term

There is also configuration documentation in the QA README.  It would benefit from a more systematic set of documentation.

https://github.com/samvera/questioning_authority/tree/min_context#configuring-a-lod-authority

**Comment by elrayle** [comment]
The json version of the API is...
https://github.com/samvera/questioning_authority/blob/min_context/lib/generators/qa/apidoc/templates/public/qa/apidoc/apidoc.json
