### ISSUE TITLE
LCDGT does not include Variant in search results

### ISSUE THREAD

**Issue by elrayle** [LD4P/qa_server#194]
authority: LCDGT
search query: West Indian Americans
loc id: dg2015060552
loc rwo uri: <http://id.loc.gov/authorities/demographicTerms/dg2015060552>

id.loc.gov has these triples related to Citation note, source, status...

```
<http://id.loc.gov/authorities/demographicTerms/dg2015060552> <madsrdf:hasVariant> _:bnode11
_:bnode11 <madsrdf:variantLabel> "Americans, West Indian"@en .
```

curl -L -D - -H 'Accept: application/n-triples' 'http://services.ld4l.org/ld4l_services/loc_demographics_batch.jsp?query=West%20Indian%20Americans&maxRecords=1&startRecord=1&lang=en'

The results returned from the cache has the following triples related to Citation source and note...

```
<http://id.loc.gov/authorities/demographicTerms/dg2015060552> <madsrdf:hasVariant> _:b2 .
```

Missing triple...

```
_:b2 <madsrdf:variantLabel> "Americans, West Indian"@en .
```

### Related Issues

#191 LCDGT does not labels or ids for broader and narrower
#192 LCDGT does not include Citation note, source, or status in search results
#195 LCDGT does not include Related in search results
#196 LCDGT does not include Earlier Established Form in search results
#26 Request authority LCDGT (Library of Congress Demographic Group Terms) be supported

**Comment by eichmann** [comment]
@elrayle fix deployed and ready for validation.

**Comment by elrayle** [comment]
Closing: Confirmed Variant is in search results.
