### ISSUE TITLE
LCDGT does not include Related in search results

### ISSUE THREAD

**Issue by elrayle** [LD4P/qa_server#195]
authority: LCDGT
search query: African Americans
loc id: dg2015060362
loc rwo uri: <http://id.loc.gov/authorities/demographicTerms/dg2015060362>

id.loc.gov has these triples related to Citation note, source, status...

```
<http://id.loc.gov/authorities/demographicTerms/dg2015060362> <skos:related> <http://id.loc.gov/authorities/demographicTerms/dg2015060859>
<http://id.loc.gov/authorities/demographicTerms/dg2015060859> <skos:prefLabel> "Blacks"@en .
```

curl -L -D - -H 'Accept: application/n-triples' 'http://services.ld4l.org/ld4l_services/loc_demographics_batch.jsp?query=African%20Americans&maxRecords=1&startRecord=1&lang=en'

The results returned from the cache has the following triples related to Citation source and note...

```
<http://id.loc.gov/authorities/demographicTerms/dg2015060362> <skos:related> <http://id.loc.gov/authorities/demographicTerms/dg2015060859>
```

Missing triple...

```
<http://id.loc.gov/authorities/demographicTerms/dg2015060859> <skos:prefLabel> "Blacks"@en .
```

### Related Issues

#191 LCDGT does not labels or ids for broader and narrower
#192 LCDGT does not include Citation note, source, or status in search results
#194 LCDGT does not include Variant in search results
#196 LCDGT does not include Earlier Established Form in search results
#26 Request authority LCDGT (Library of Congress Demographic Group Terms) be supported

**Comment by eichmann** [comment]
@elrayle skos:related prefLabels and lccns now appear.

**Comment by elrayle** [comment]
Closing: Verified in search results using...

http://localhost:3000/authorities/search/linked_data/locdemographics_ld4l_cache?q=African%20Americans&maxRecords=5&context=true
