### ISSUE TITLE
LCDGT does not include Earlier Established Form in search results

### ISSUE THREAD

**Issue by elrayle** [LD4P/qa_server#196]
authority: LCDGT
search query: Lakota (North American people)
loc id: dg2015060241
loc rwo uri: <http://id.loc.gov/authorities/demographicTerms/dg2015060241>

id.loc.gov has these triples related to Citation note, source, status...

```
<http://id.loc.gov/authorities/demographicTerms/dg2015060241> <madsrdf:hasEarlierEstablishedForm> _:bnode83 .
_:bnode83 <madsrdf:variantLabel> "Lakota Indians"@en .
```

curl -L -D - -H 'Accept: application/n-triples' 'http://services.ld4l.org/ld4l_services/loc_demographics_batch.jsp?query=Lakota%20(North%20American%20people)&maxRecords=1&startRecord=1&lang=en'

The results returned from the cache has the following triples related to Citation source and note...

```
<http://id.loc.gov/authorities/demographicTerms/dg2015060241> <madsrdf:hasEarlierEstablishedForm> _:b28 .
```

Missing triple...

```
_:b2 <madsrdf:variantLabel> "Lakota Indians"@en .
```

### Related Issues

#191 LCDGT does not labels or ids for broader and narrower
#192 LCDGT does not include Citation note, source, or status in search results
#194 LCDGT does not include Variant in search results
#195 LCDGT does not include Related in search results
#26 Request authority LCDGT (Library of Congress Demographic Group Terms) be supported

**Comment by eichmann** [comment]
@elrayle madsrdf:hasEarlierEstablishedForm now appears.

**Comment by elrayle** [comment]
@eichmann Can you double check the source data?

loc uses `madsrdf:variantLabel`
the cache returned `madsrdf:authoritativeLabel`

I don't have any problem adding authoritativeLabel to the ldpath in addition to variantLabel, but I am wondering why the difference.  I suppose it could be that LC download and LC live have different data.

**Comment by eichmann** [comment]
Looking at the results, I'm seeing blank nodes with mads variantLabels...

**Comment by elrayle** [comment]
When I execute 

```
curl -L -D - -H 'Accept: application/n-triples' 'http://services.ld4l.org/ld4l_services/loc_demographics_batch.jsp?query=Lakota%20(North%20American%20people)&maxRecords=1&startRecord=1&lang=en'
```

I get...

```
<http://id.loc.gov/authorities/demographicTerms/dg2015060241> <http://www.loc.gov/mads/rdf/v1#hasEarlierEstablishedForm> _:b3 .	
_:b3 <http://www.loc.gov/mads/rdf/v1#authoritativeLabel> "Lakota Indians"@en .
_:b3 <http://www.loc.gov/mads/rdf/v1#elementList> _:b4 .
_:b3 <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://www.loc.gov/mads/rdf/v1#Authority> .
```

**Comment by eichmann** [comment]
@elrayle Those are the triples... the query snags all triples with the referenced blank node as subject.  The variantLabel blank node triples are referenced by hasVariant.

**Comment by eichmann** [comment]
Is it possible that some labels so pointed at are authoritative, and others variant?

**Comment by elrayle** [comment]
@sf433 RE: DGT earlier form…
The spreadsheet says to use variantLabel for earlier form, but I don’t find any in the data.  I do find it under authoritativeLabel.

This gets lots of hits…
```
PREFIX madsrdf:    <http://www.loc.gov/mads/rdf/v1#>
SELECT ?s ?o
WHERE
  { ?s madsrdf:hasEarlierEstablishedForm ?b .
    ?b madsrdf:authoritativeLabel ?o .
} limit 10
```

This gets 0 results…
```
PREFIX madsrdf:    <http://www.loc.gov/mads/rdf/v1#>
SELECT ?s ?o
WHERE
  { ?s madsrdf:hasEarlierEstablishedForm ?b .
    ?b madsrdf:variantLabel ?o .
} limit 10
```

**Comment by elrayle** [comment]
Closing:  Fixed by PR https://github.com/cul-it/qa_server/pull/132
