### ISSUE TITLE
Add LOC Subject Schemes to list of available lookups

### ISSUE THREAD

**Issue by mmcgee** [LD4P/qa_server#199]
**Describe the bug**
What went wrong? What did you expect to happen?

- What is the impact on your work? (can't work / work stoppage; workaround exists; minor issue)
- What environment are you in? (stage or production)
- What OS and browser are you using? (Mac/Windows; Safari, Firefox, etc.)
- If you're cataloging, what Resource Template were you using (name or ID)

**Please include a screenshot**
(Mac: shift-command-4; Windows: ; then drag the image file into the issue)

**Comment by elrayle** [comment]
Closing... fixed in Sinopia PR https://github.com/LD4P/sinopia_editor/pull/1294
