### ISSUE TITLE
LCGFT does not include Citation note, source, or status in search results

### ISSUE THREAD

**Issue by elrayle** [LD4P/qa_server#200]
**HOLD ON THIS ISSUE** until the rewrite of the extended context (issue #50) for LCGFT.

----

authority: LCGFT
search query: Cartographic materials
loc id: gf2011026113
loc rwo uri: <http://id.loc.gov/authorities/genreForms/gf2011026113>

id.loc.gov has these triples related to Citation note, source, status...

```
<http://id.loc.gov/authorities/genreForms/gf2011026113> <madsrdf:hasSource> _:bnode80 .
_:bnode80 <madsrdf:citation-source> "Glossary of the mapping sciences, 1994:" . 
_:bnode80 <madsrdf:citation-note> "cartographic (associated with cartography; having to do with mapping in the general sense)"@en . 
_:bnode80 <madsrdf:citation-note> "found" .
```

curl -L -D - -H 'Accept: application/n-triples' 'http://services.ld4l.org/ld4l_services/loc_genre_batch.jsp?query=Cartographic%20materials&maxRecords=1&startRecord=1&lang=en'

The results returned from the cache has the following triples related to Citation source and note...

```
<http://id.loc.gov/authorities/genreForms/gf2011026113> <madsrdf:hasSource> _:b2 .
```

Missing triple...

```
_:b2 <madsrdf:citation-source> "Glossary of the mapping sciences, 1994:" . 
_:b2 <madsrdf:citation-note> "cartographic (associated with cartography; having to do with mapping in the general sense)"@en . 
_:b2 <madsrdf:citation-note> "found" .
```

### Related Issues

#50 Add Subauthorities to DAVE and QA for LCGFT

**Comment by eichmann** [comment]
Fix deployed to production.

**Comment by elrayle** [comment]
Confirmed fixed.
