### ISSUE TITLE
when searching (in any of our search components), search string should match strings with same letters plus diacritics

### ISSUE THREAD

**Issue by michelleif** [LD4P/qa_server#201]
see also https://github.com/LD4P/sinopia_editor/issues/1287 for some examples, https://github.com/LD4P/sinopia_editor/issues/1287 applies to our search of data created in Sinopia.

this ticket is to request that for QA searches, search string should match strings with same letters plus diacritics

**Comment by sfolsom** [comment]
More on diacritic and non-Roman character concerns can be found in https://docs.google.com/document/d/1UxSeZ9xWpIZ__UxzMAtJGlXUrRzY-yZ3OukZNw2FDrg/edit# (pages 14-15, 19-22).

**Comment by briesenberg07** [comment]
+1 to 
>for QA searches, search string should match strings with same letters plus diacritics

Thanks all!

**Comment by elrayle** [comment]
PR #362 adds tests for Tanaka, Shōzō

### Tests Results

Authority: LOCNAMES_RWO_LD4L_CACHE:
Subauthority:  person

#### using old indexing approach:

```
not found     Tanaka, Shozo
not found     Tanaka, Shōzō
not found     田中正造
```

#### using new indexing approach:

```
found as expected            Tanaka, Shozo
found at 12; expected by 5   Tanaka, Shōzō
found as expected            田中正造

**Comment by elrayle** [comment]
Recommended tests from other diacritic and special character examples described in [Harvard's Look up feedback](https://docs.google.com/document/d/1UxSeZ9xWpIZ__UxzMAtJGlXUrRzY-yZ3OukZNw2FDrg/edit#).  This list does not address examples of general relavancy.

----
**Authority:** LOCSUBJECTS
**Subauthority:** N/A
**Expected URI:** http://id.loc.gov/authorities/subjects/sh2005004632
**Queries:**
* heavy metal
* guitar music
* guitar music (
* Guitar music (Heavy metal) 

----
**Authority:** LOCNAMES_RWO
**Subauthority:** person
**Expected URI:** http://id.loc.gov/rwo/agents/no2003094541
**Queries:**
* Endalageta Kabada
* ʼEndālagétā Kabada

----
**Authority:** LOCNAMES_RWO
**Subauthority:** person
**Expected URI:** http://id.loc.gov/rwo/agents/n2013003006
**Queries:**
* Genkai Shosetsu Kenkyukai
* Genkai Shōsetsu Kenkyūkai
* 限界小說研究会

----
**Authority:** LOCNAMES_RWO
**Subauthority:** person
**Expected URI:** http://id.loc.gov/rwo/agents/n79068416
**Queries:**
* Tolstoy, Leo
* tolstoi, lev
* Tolstoĭ, Lev
* Толстой, Лев
* Толстой, Лев, граф, 1828-1910
* טאלסטאי, ליעװ
* レオ.トルストイ
* لئون تولستوى
* 托爾斯泰, 列夫

**Comment by elrayle** [comment]
PR #362 and PR #364 added tests for all examples in this issue.

**Comment by elrayle** [comment]
There are some exceptions that we haven't been able to address, but this is considered complete.
