### ISSUE TITLE
maxRecords not honored when there is an exact match for the query

### ISSUE THREAD

**Issue by elrayle** [LD4P/qa_server#202]
authority: LCDGT
search query: 'dancers' vs. 'Dancers'
loc id: dg2015060747
prefLabel: 'Dancers'
loc rwo uri: http://id.loc.gov/authorities/demographicTerms/dg2015060747

When performing these two queries, 'Dancers' is an exact match for dg2015060747. 'dancers' is not an exact match.

```
q=dancers&maxRecords=1      # return 1 result
q=Dancers&maxRecords=1      # returns 6 results
```

**Comment by elrayle** [comment]
Retested...

If maxRecords > total number of matches...
```
q=dancers&maxRecords=10      # returns 5 results
q=Dancers&maxRecords=10      # returns same 5 results
```

If maxRecords < total number of matches...
```
q=dancers&maxRecords=4      # returns 4 results
q=Dancers&maxRecords=4      # returns 3 results
```

@eichmann I believe this is happening because one of the matches for `Dancers` is n exact match.

**Comment by eichmann** [comment]
I think my counting patch likely resolved this.

**Comment by elrayle** [comment]
Verified fixed.  Both the following queries return the same results with the same exact match as the first result.

https://lookup.ld4l.org/authorities/search/linked_data/locdemographics_ld4l_cache?q=dancers&maxRecords=5
https://lookup.ld4l.org/authorities/search/linked_data/locdemographics_ld4l_cache?q=Dancers&maxRecords=5
