### ISSUE TITLE
LCSH results in alphabetical order?

### ISSUE THREAD

**Issue by jbaxmeyer** [LD4P/qa_server#203]
Can the results from LCSH be in alphabetical order?
<img width="353" alt="LCSHooo" src="https://user-images.githubusercontent.com/7747876/63175254-a5ca8200-c011-11e9-8382-bf4031a2bca6.PNG">

**Comment by eslao** [comment]
This would be nice to have, but would it be possible to give the user the option to toggle between alphabetical order and best match order?

**Comment by elrayle** [comment]
This and several other similar issues related to ordering of results or the approach to performing the search are marked as low priority.  This issue is being closed as `wontfix`, but can be reopened if it becomes a priority.

See also: 
* Issue #190
* Issue #134
