### ISSUE TITLE
LCNAF Context: Show 670 field

### ISSUE THREAD

**Issue by michelleif** [LD4P/qa_server#204]
creating issue for greta @ stanford re context on LCNAF search:
"... it's useful to see the 670 field in addition to the 3xx fields but i realize real estate is limited."

**Comment by sfolsom** [comment]
is it not? I'm seeing the notes here:
<img width="588" alt="Screen Shot 2019-10-18 at 5 34 30 PM" src="https://user-images.githubusercontent.com/8257258/67129858-b3e17e00-f1cd-11e9-8115-e77989010402.png">

**Comment by michelleif** [comment]
this was feedback from user testing so maybe it wasn't showing at that point? if you say it's there, then I'll close this.
