### ISSUE TITLE
Request for ISO 639-3 Language Codes

### ISSUE THREAD

**Issue by a-cohen** [LD4P/qa_server#209]
Data Source: ISO 639-3 Language Codes
URL: https://iso639-3.sil.org/
API: no API, but available for download here https://iso639-3.sil.org/code_tables/download_tables

An important vocabulary used by our metadata team.

**Comment by sfolsom** [comment]
Hmmm... this one is a little different because to my knowledge it's not RDF. Would the LOC language code lists based on ISO639-1, ISO639-2, and ISO639-5 (as RDF) serve your needs? Or are you expecting to use the codes directly as non-RDF resources?

**Comment by sfolsom** [comment]
I think this is getting taken care of by https://github.com/LD4P/sinopia_editor/issues/1230
