### ISSUE TITLE
Request for LOC Special Playback Characteristics

### ISSUE THREAD

**Issue by NancyL** [LD4P/qa_server#211]
_Please only use this issue template for LD4P2 requests for a new data source to be added to QA. If your requesting changes to how a dataset currently available in QA is treated, please use the indexing bug issue template._

__For LD4P2 partners and cohorts:__

Please perform each task listed below. (Email sf433 @ cornell dot edu with questions):
- [x ] Please consult the LD4P2 QA Authority Support Plan (https://github.com/LD4P/qa_server/wiki/Authority-Lookup-Support-Plan-for-Sinopia) to confirm the dataset isn't already being supported.
- [x ] Identify the data source: Special Playback Characteristics http://id.loc.gov/vocabulary/mspecplayback.html 
- [x ] Contextual information is not necessary. The vocabulary is already listed on the following spreadsheet: https://docs.google.com/spreadsheets/d/1rPvEoP9iYNkxJ0eWC8gXe3ci7e6mhW0da59xkGhadi0/edit?usp=sharing.  

This vocabulary is part of the basic LD4P profiles for BluRay DVD & Sound Recording--CD. For CDs, it is required by the PCC BSR when applicable. It is a short vocabulary--only a dropdown list is necessary.

Next steps: 

Once the above actions have taken place, a link to a YAML file will be shared with the requestor via a comment in the issue in order to complete Accuracy Test, https://github.com/LD4P/qa_server/wiki/Writing-Tests-for-an-Authority#accuracy-test. Edit directly the YAML file in Github, save. Create a Pull Request to be reviewed. Be sure to including a meaningful commit message (e.g. adding accuracy tests for Authority X). 

Context on Accuracy Tests: In order to make sure the QA search behavior (recall and relevancy) are meeting expectations, QA uses YAML to define test parameters. These parameters include the ability to declare for a particular text string searched, the results should include a particular resource (identified by a URI) and what is the maximum position in the results the resource should be found.)

_Please note, all requests for new data sources in QA will be prioritized by the LD4P2 project. Due to time restrictions there is no guarantee that all requests will be added to QA during the lifetime of the LD4P2 grant; regardless of resources it is still useful to know which datasets the community would find useful in such a lookup service._

**Comment by sfolsom** [comment]
Not trying to push back on this request, but just confirming... would an LOC direct list lookup added to SInopia's authority config be sufficient for now similar to https://github.com/LD4P/sinopia_editor/blob/master/static/authorityConfig.json#L1765? 

Also, a side note: we're working with LOC to get a dump of all the small vocabs to load and configure in one fell swoop, similar to the addition of the various RDA vocabs.

**Comment by NancyL** [comment]
Direct list lookup is fine—there is really no other useful information.

**Comment by NancyL** [comment]
And doing them all in one fell swoop would also be perfect
________________________________

**Comment by sfolsom** [comment]
Pull request in to add the LOC direct lookup as a list: https://github.com/LD4P/sinopia_editor/pull/1600

Will continue to try to get all small LOC vocabs in as one job in QA.
