### ISSUE TITLE
No Context for MeSH

### ISSUE THREAD

**Issue by bushmanb** [LD4P/qa_server#215]
When will context for MeSH be available?

**Comment by elrayle** [comment]
@bushmanb I'm working on the extended context for MeSH today.  I have a question for you...

* Entry terms appear on row 12 & 13 of the [spreadsheet](https://docs.google.com/spreadsheets/d/1rPvEoP9iYNkxJ0eWC8gXe3ci7e6mhW0da59xkGhadi0/edit#gid=2113261477).  Should these be separate contexts with separate names or combined into a single Entry terms context?

* For Entry terms, I notice you are using inverse relationships.  This is fine syntax, but can perform slow.  Two options:  1) we could try the extended context without Entry terms and see how it performs and then try adding it if performance is acceptable, 2) include Entry terms and remove it if performance is not acceptable

There are a few others that are also using the inverse relationship.  You may end up wanting to evaluate the cost-to-value ratio of including these.

@eichmann Any thoughts on your side about slow inverse relationships?  I'm basing this on observations of slowness for LOC RWO Names.

**Comment by elrayle** [comment]
@bushmanb On line 15 of the spreadsheet, it reuses the display name of `Related concept`.  I'm wondering if this should be `Scope note`, as that is what is retrieved.

**Comment by bushmanb** [comment]
@elrayle you are correct on both counts. Lines 12 and 13 can be combined into Entry Terms.  Line 15 should be Scope note, not Related concept.  As for the slowness issue, we would like to go with option 2) include Entry terms and remove it if performance is not acceptable.

**Comment by elrayle** [comment]
@bushmanb You marked all extended context as visible in the Display except Variant label.  Is this correct?

**Comment by elrayle** [comment]
@bushmanb Line 18 and 19 have the same display label `Use instead`.  Should they be combined or should linke 19 have display label `Mapped to`?

**Comment by bushmanb** [comment]
@elrayle  Yes, all extended content except Variant label should be visible in the display.  Line 18 and 19 can be combined into Use instead.

**Comment by elrayle** [comment]
@bushmanb We have been using mesh:prefLabel as the primary label.  The spreadsheet identifies rdfs:label as the primary label.  I just want to confirm with you that you want to make that change.

**Comment by bushmanb** [comment]
@elrayle That is correct, it should rdfs:label.  mesh:prefLabel is for the terms and we want the descriptors.

**Comment by elrayle** [comment]
@bushmanb Should mesh have 3 subauthorities: TopicalDescriptor, GeographicalDescriptor, and PublicationType?

**Comment by bushmanb** [comment]
@elrayle  That is correct, there are three types of descriptors in MeSH, topical, geographic and Publication Type.  These correspond to what you wound enter in the MARC 650, 651 and 655 fields.

**Comment by sfolsom** [comment]
I believe this work has been completed. We can reopen or create a new issue if there's more work to be done on the MESH lookup.
