### ISSUE TITLE
LOC geographic [names] is showing non-geographic hits

### ISSUE THREAD

**Issue by michelleif** [LD4P/qa_server#240]
Stanford cataloging team reports that in Monograph template, a field that's a lookup to `LOC geographic [names]` is returning non-geographic hits.

Going to https://lookup.ld4l.org/authority_list to check,the sample searches are the same for LOCNAMES_LD4L_CACHE with and without the geographic subauthority specified...it seems that specifying the geographic subauthority is not doing anything.

`https://lookup.ld4l.org/authorities/search/linked_data/locnames_ld4l_cache/geographic?q=Cayuga&maxRecords=4&context=true`

and

`https://lookup.ld4l.org/authorities/search/linked_data/locnames_ld4l_cache?q=Cayuga&maxRecords=4&context=true`

give the same results

is something wrong with the geographic sub-authority aspect?

**Comment by elrayle** [comment]
DUP of #248 which has a bit more information at this point, so closing this issue.
