### ISSUE TITLE
LOC geographic [names] (QA) is showing non-geographic entities

### ISSUE THREAD

**Issue by sfolsom** [LD4P/qa_server#248]
Right now Corporate Names and other entity types are often drowning out the Geographic Names in the LOC geographic [names] (QA) lookup.

for searches like https://lookup.ld4l.org/authorities/search/linked_data/locnames_ld4l_cache/geographic?q=Cayuga&maxRecords=4&context=true (the geographic subauth for LCNAF) the expectation is that only geographic entities would return, but we see a lot of Corporate Names.

Here's another example: https://lookup.ld4l.org/authorities/search/linked_data/locnames_ld4l_cache/geographic?q=New%20York%20City&maxRecords=4&context=true (in this case we Corporate Names and Name Titles.)

**Comment by sfolsom** [comment]
classes and property paths are defined here: https://docs.google.com/spreadsheets/d/1rPvEoP9iYNkxJ0eWC8gXe3ci7e6mhW0da59xkGhadi0/edit#gid=745128104

**Comment by elrayle** [comment]
Screen shot from @michelleif 


![](https://user-images.githubusercontent.com/48070028/77564111-71f4ec00-6e7f-11ea-966e-6e3038db6a4e.PNG)

**Comment by elrayle** [comment]
Another example in closed dup issue #240

**Comment by jimfhahn** [comment]
I wanted to ask if there could be improvements to how LC geographic names appear in lookup. 
![Screen Shot 2020-12-04 at 11 03 12 AM](https://user-images.githubusercontent.com/1310509/101202818-64f3e380-362f-11eb-9233-2bda287a9725.png)
I've attached a screenshot of a search for Chicago, which brought up an organization name and personal names. (This was in the Monograph Instance (BF2) Un-Nested template.) it is a publication place field, so those results are unexpected. 

I think you have to scroll through a lot of hits to get to Chicago (Ill.). Could the publication place field lookup be limited to just geographic names? Has this been suggested already?

**Comment by sfolsom** [comment]
I think we can close this issue. @eichmann you fixed this right? I don't see Corporate Name with the Geographics.

**Comment by eichmann** [comment]
This should be resolved....
