### ISSUE TITLE
Request authority LCDGT (Library of Congress Demographic Group Terms) be supported

### ISSUE THREAD

**Issue by AdamSchiff** [LD4P/qa_server#26]
_Please only use this issue template for LD4P2 requests for a new data source to be added to QA. If your requesting changes to how a dataset currently available in QA is treated, please use the indexing bug issue template._

__For LD4P2 partners and cohorts:__

More information about making a request can be found at https://wiki.duraspace.org/display/LD4P2/Request+a+New+Dataset+For+QA

Please perform each task listed below. (Email sf433 @ cornell dot edu with questions):

- [x] Identify the data source: (Include the Data Source Name and its homepage URL)
- [x] Add a new tab and indexing information for the data source to the following spreadsheet: https://docs.google.com/spreadsheets/d/1rPvEoP9iYNkxJ0eWC8gXe3ci7e6mhW0da59xkGhadi0/edit?usp=sharing.
- [ ] Add a YAML test file to https://github.com/cul-it/qa_server/tree/master/config/authorities/linked_data/scenarios; please provide here a link to the YAML file related to this request. 
      - See the definition of YAML keys: (link coming soon). 
      - YAML Example: https://github.com/cul-it/qa_server/blob/master/config/authorities/linked_data/scenarios/locgenres_ld4l_cache_validation.yml

_Please note, all requests for new data sources in QA will be prioritized by the LD4P2 project. Due to time restrictions there is no guarantee that all requests will be added to QA during the lifetime of the LD4P2 grant; regardless of resources it is still useful to know which datasets the community would find useful in such a lookup service._

**Comment by CECSpecialistI** [comment]
New tab added to spreadsheet: [https://docs.google.com/spreadsheets/d/1rPvEoP9iYNkxJ0eWC8gXe3ci7e6mhW0da59xkGhadi0/edit#gid=612799256]

**Comment by elrayle** [comment]
### Links for Testing in Production

This authority can be used now at the following example links...

SEARCH:  https://lookup.ld4l.org/authorities/search/linked_data/locdemographics_ld4l_cache?q=workers&maxRecords=4

FETCH:  https://lookup.ld4l.org/authorities/fetch/linked_data/locdemographics_ld4l_cache?uri=http%3A%2F%2Fid%2Eloc%2Egov%2Fauthorities%2FdemographicTerms%2Fdg2015060460

### Create Accuracy Tests

REFERENCE:  [Writing-Tests-for-an-Authority](https://github.com/LD4P/qa_server/wiki/Writing-Tests-for-an-Authority)

ADD ACCURACY TESTS TO:  [locdemographics_ld4l_cache_validation.yml](https://github.com/LD4P/qa_server/blob/master/lib/generators/qa_server/templates/config/authorities/linked_data/scenarios/locdemographics_ld4l_cache_validation.yml)

### Add Comment in this Issue

Add a comment to this issue when your tests are done.  I will add to production site.  Then you will be able to run the tests at...

TEST AT: https://lookup.ld4l.org/check_status?utf8=%E2%9C%93&authority=LOCDEMOGRAPHICS_LD4L_CACHE&validation_type=connections

**Comment by elrayle** [comment]
The provided accuracy tests (PR #46) are in production.  The results are not immediately what we want.  

![image](https://user-images.githubusercontent.com/6855473/51060483-e9619700-15bd-11e9-8c94-a68d1401f882.png)

@eichmann and I are exploring the following changes to the indexing based on the spreadsheet information and some general processing discussions in the larger authorities community.

* ensure the specified search related fields are being searched
  * prefLabel (highest weighting)
  * broader/prefLabel
  * narrower/prefLabel
  * hasVariant/variantLabel
  * hasEarlierEstablishedForm/variantLabel
  * related/prefLabel
* weight an exact match of the highest weighted field (e.g. prefLabel) higher than a general match

**Comment by elrayle** [comment]
- [X] owner - @AdamSchiff 
- [x] data in D.A.V.E
- [x] configured in QA
  - [x] basic term and search configuration
  - [ ] subauthority configuration - pending info from @eichmann about whether there are any subauthorities
- [x] connection tests
  - [x] basic term and search test 
    - [x] written
    - [x] on production server
  - [ ] subauthority connection tests
    - [ ] written
    - [ ] on production server
- [x] accuracy tests
    - [x] written
    - [x] on production server
    - [ ] passing - 3 passing, 4 failing - working on tweaking the indexing approach

**Comment by eichmann** [comment]
Blending the spreadsheet configuration with @elrayle 's Jan 16 configuration, we now score prefLabel at 10, altlabel at 2 and broader/narrower at 1 for boost values.  Let's see what that does to scoring.  We're set up to tweak scores (and add additional search items) pretty much at will now.

**Comment by sfolsom** [comment]
Hi @AdamSchiff, I'm updating the spreadsheet that I believe you worked on to adhere to changes we've made to the spreadsheet structure (https://docs.google.com/spreadsheets/d/1rPvEoP9iYNkxJ0eWC8gXe3ci7e6mhW0da59xkGhadi0/edit#gid=612799256), and I've noticed that it looks like there's an expectation that QA would allow the cataloger to look up and link to madsrdf:Collections like http://id.loc.gov/authorities/demographicTerms/collection_LCDGT_Age. Is that the request? It would seem to make more sense to me to look up and link to the skos:Concepts and note what madsrdf:Collections the concept is a member of in the contextual information QA brings back. If the latter I can make changes to the spreadsheet to reflect this. If the former, can you confirm in what scenario you intend to look up and link to madsrdf:Collections? Are you planning to create demonyms outside of LC and want to still linke them to the id.loc.gov collections? If so, we might want to consider adding more context in QA for the madsrdf:Collections.

**Comment by AdamSchiff** [comment]
Hi @sfolsom, I have checked with our metadata specialists here and they agree with you that it would make more sense to look up and link to the skos:Concepts and note what madsrdf:Collections the concept is a member of in the contextual information QA brings back.

Theo Gerontakos wrote: "I think our entry reflects a poorly-formed understanding of QA lookups and of Sinopia – which is understandable, since we created that spreadsheet tab a long time ago.

After a cataloger enters a demographic term, I believe we just wanted the retrieval to include information about the collection to which a given concept might belong. Steven is correct, it makes more sense to look up the skos:Concept and then display a note about the Collection which the Concept is part of. We wouldn’t want to ~search~ the collections for the term entered by a cataloger – that wouldn’t make much sense (catalogers will enter terms like “Infants” and “teenagers” but not “age”) – we only wanted Sinopia to display info as part of the display following a lookup, to help catalogers understand the term for which a URI was retrieved."

**Comment by sfolsom** [comment]
Great! Thanks for the feedback.

**Comment by sfolsom** [comment]
Updated the spreadsheet. For lookups with context for SVDE, please implement related LDPath in DAVE and QA: https://docs.google.com/spreadsheets/d/1rPvEoP9iYNkxJ0eWC8gXe3ci7e6mhW0da59xkGhadi0/edit#gid=612799256

**Comment by elrayle** [comment]
### Context & Queries

The following table identifies extended context that should be added and queries that produce results with values for those context fields.

| extended context | query (result idx) | expected value | comments |
| ----------------- | ------ | --------------- | ----------- |
| Preferred label = skos:prefLabel | workers (0) | Social workers | |
| Broader = skos:broader / skos:prefLabel | workers (1) | [http://id.loc.gov/authorities/demographicTerms/dg2015060218] | shows label, but not ID |
| Narrower = skos:narrower / skos:prefLabel | workers (2) | [http://id.loc.gov/authorities/demographicTerms/dg2015060219] | shows label, but not ID |
| Variant = madsrdf:hasVariant / madsrdf:variantLabel | indian (0) | [Americans, West Indian] | seen at id.loc.gov, but not from QA; likely requires change in data returned from cache |
| Earlier form = madsrdf:hasEarlierEstablishedForm / madsrdf:variantLabel |  () | [] | |
| Related = skos:related | () | [] | |
| Note = skos:note | lao (1) | [Ethnic Lao. For residents of Laos in general see [Laotians.]] | |
| Example = skos:example | lao (1) | [Note under [Laotians]] | |
| Citation note = madsrdf:hasSource / madsrdf:citation-note | indian (0) | [(American literature--West Indian American authors)] | seen at id.loc.gov, but not from QA; likely requires change in data returned from cache |
| Citation source = madsrdf:hasSource / madsrdf:citation-source | indian (0) | [LCSH, Aug. 4, 2015:] | seen at id.loc.gov, but not from QA; likely requires change in data returned from cache |
| Citation status = madsrdf:hasSource / madsrdf:citation-status | indian (0) | [found, ...] | seen at id.loc.gov, but not from QA; likely requires change in data returned from cache |

**Comment by elrayle** [comment]
@AdamSchiff Can you identify queries at id.loc.gov that includes data for `madsrdf:hasEarlierEstablishedForm / madsrdf:variantLabel` and `skos:related`?

**Comment by elrayle** [comment]
@eichmann Can you update the SPARQL for LCDGT to return all extended context.  See the comments in the Context & Queries table to see which context is not coming back.  I don't have queries for earlier form and related yet, but I'd be surprised if those are coming back from the cache.  Hopefully, I'll have a way to verify that soon.

**Comment by sfolsom** [comment]
> @AdamSchiff Can you identify queries at id.loc.gov that includes data for `madsrdf:hasEarlierEstablishedForm / madsrdf:variantLabel` and `skos:related`?

I was able to come up with a skos:related search (see above), but the madsrdf:hasEarlierEstablishedForm / madsrdf:variantLabel might need to be madsrdf:hasEarlierEstablishedForm / madsrdf:authoritativeLabel. But first I'd want @eichmann to take a look, because all of the values seem to be a blank node with a madsrdf:authoritativeLabel of "Presidents".

**Comment by gerontakos** [comment]
> @AdamSchiff Can you identify queries at id.loc.gov that includes data for madsrdf:hasEarlierEstablishedForm / madsrdf:variantLabel and skos:related?

I'm supplying this reply for @AdamSchiff.

Query for "Earlier Form":
**Extended Context:**
    Earlier form = madsrdf:hasEarlierEstablishedForm / madsrdf:variantLabel
**Query (result idx):**
    Lakota (North American people)
**Expected value:**
    Lakota Indians

Query for "Related":
**Extended Context:**
    skos:related / skos:prefLabel
**Query (result idx):**
    African Americans
**Expected value:**
    Blacks

I hope that makes sense.

I see the madsrdf properties have caused some trouble. Is it possible that you've only dumped (assuming you're using data dumps) LCDGT as skos not, as is also offered at id.loc.gov, as madsrdf?

The skos dump appears to have excluded all the "Earlier Forms" included in madsrdf. 

For the record, I found 10 earlerForm labels in the madsrdf, any of which could be used in the query:
| query                                                               | expectedValue = EarlierForm
=========================================================
| "Choctaw (North American people)"@en        | "Choctaw Indians"@en
| "Apache (North American people)"@en          | "Apache Indians"@en
| "Fluminense"@en                                            | "Rio de Janeiro, Brazil, residents"@en
| "Presidents (Rulers)"@en                                 | "Presidents"@en
| "Cree (North American people)"@en              | "Cree Indians"@en
| "Pacific Islanders"@en                                     | "Oceanians"@en
| "People with developmental disabilities"@en   | "Developmentally disabled"@en
| "Lakota (North American people)"@en           | "Lakota Indians"@en
| "Hawaiians (Polynesian people)"@en              | "Hawaiians (Polynesians)"@en
| "Powhatan (North American people)"@en      | "Powhatan Indians"@en
-----------------------------------------------------------------------------------------------------


I hope that's useful! Let me know if you need something else.

  --Theo Gerontakos

**Comment by elrayle** [comment]
Remaining Issues:

* #191 LCDGT does not labels or ids for broader and narrower
* #192 LCDGT does not include Citation note, source, or status in search results

More to come.
