### ISSUE TITLE
Request to add Homosaurus controlled vocabulary to the QA lookup tool

### ISSUE THREAD

**Issue by JeannetteHo1** [LD4P/qa_server#303]
The Texas A&M University cohort would like to request that the Homosaurus controlled vocabulary (availble at http://homosaurus.org/) be added to the QA lookup tool.  It is an 
"international linked data" controlled vocabulary for LGBTQ terms that is intended to be a "companion vocabulary" to other established ones, such as LCSH, etc.  It was originally created by the IHLIA LGBT Heritage.  I have not seen any APIs, or an option to download the entire vocabulary, but if you go to the website, you can look up any single term and export metadata related to it.

We are planning to catalog LGBTQ-related literature for the LD4P and think that the Homosaurus terms provide much more specificity than LC subject headings. We would like to use it  in conjunction with the LC subject headings to provide greater access to these materials.

I was not able to add a tab to the spreadsheet at https://docs.google.com/spreadsheets/d/1rPvEoP9iYNkxJ0eWC8gXe3ci7e6mhW0da59xkGhadi0/edit?usp=sharing, although I have the information that  I would like to add to it.  If someone could give me permission to do it, or let me know if I should forward a separate spreadsheet, I can provide this information.

Thank you,

Jeannette Ho
Cataloging/Metadata Librarian
Texas A&M University Libraries
jaho@library.tamu.edu

**Comment by sfolsom** [comment]
@JeannetteHo1, I've given you permission to edit the spreadsheet. Please let me know if you have any questions; I'm happy to help with this request.

**Comment by JeannetteHo1** [comment]
Thanks.  I am working on filling out a portion for this thesaurus.


This is my first time documenting a controlled vocabulary in this manner, so I may  ask you to preview what I have before I add it to the spreadsheeet.


Jeannette


Jeannette Ho

Cataloging/Metadata Librarian

Texas A&M University Libraries

________________________________

**Comment by elrayle** [comment]
Download: https://homosaurus.org/v2.nt

**Comment by elrayle** [comment]
Next steps:
- [ ] indexing documentation in spreadsheet
- [ ] download and ingest
- [ ] index
- [ ] config qa
- [ ] sinopia config

**Comment by kjrawson** [comment]
Hey there! Just chiming in as someone from the Homosaurus team to let you know that we updated our URIs and are now on v3 as a result: https://homosaurus.org/v3. Feel free to reach out if you have questions!

**Comment by sfolsom** [comment]
@eichmann I've taken a first pass at context, over here: https://docs.google.com/spreadsheets/d/1rPvEoP9iYNkxJ0eWC8gXe3ci7e6mhW0da59xkGhadi0/edit#gid=809462205

Let me know if there are questions.

**Comment by elrayle** [comment]
This is now in production.
