### ISSUE TITLE
Getting back the wrong responses for special playback characteristics

### ISSUE THREAD

**Issue by sfolsom** [LD4P/qa_server#321]
The special playback characteristics lookup has the same values as the playback channels lookup instead of ones it should have. (RDA_REGISTRY_LD4L_CACHE and config_playback_channels and special_playback are subauthorities)

**Comment by elrayle** [comment]
Observations looking at the configs for Sinopia.  There are 4 configs related to playback...

```
{
    "label": "RDA Registry configuration of playback channels (QA)",
    "uri": "urn:ld4p:qa:rda_registry_ld4l_cache:config_playback_channels",
    "authority": "rda_registry_ld4l_cache",
    "subauthority": "config_playback_channels",
    "language": "en",
    "component": "lookup"
  },
 {
    "label": "RDA Registry special playback characteristics (QA)",
    "uri": "urn:ld4p:qa:rda_registry_ld4l_cache:special_playback",
    "authority": "rda_registry_ld4l_cache",
    "subauthority": "special_playback",
    "language": "en",
    "component": "lookup"
  },
 {
    "label": "playback channels",
    "uri": "https://id.loc.gov/vocabulary/mplayback",
    "component": "list"
  },
 {
    "label": "special playback characteristics",
    "uri": "https://id.loc.gov/vocabulary/mspecplayback",
    "component": "list"
  },
```

**Comment by NancyL** [comment]
We are actively developing music & DVD templates and this is a necessary vocabulary. Is there any way that we can get this fixed in the near future?

**Comment by NancyL** [comment]
This is about LOC mspecplayback. It is providing the vocab for mplayback.

**Comment by sfolsom** [comment]
Confirmed: Configurations, etc. are now aligned with the property vocabularies.
