### ISSUE TITLE
LOC geographic names QA contains non-geographic names

### ISSUE THREAD

**Issue by RobertRohr** [LD4P/qa_server#326]
The LOC geographic [names] (QA) lookup brings up headings that are not geographic names. When using it in Sinopia stage, it also brings up titles and organization names. It should really be limited to geographic names. 
![LOC_Geographic_Names_QA](https://user-images.githubusercontent.com/48070028/77564111-71f4ec00-6e7f-11ea-966e-6e3038db6a4e.PNG)

**Comment by elrayle** [comment]
DUP of #248... closing
