### ISSUE TITLE
Create basic Discogs authority for QA

### ISSUE THREAD

**Issue by tworrall** [LD4P/qa_server#34]
Adapt the authority used in the initial Discogs test app.

**Basic features**
 1. Search url returns returns Discogs image and concatenated info: title, year, label (formats?)
 2. The "show" URL returns JSON object
 3. Must support Discogs' consumer key and secret authentication (required by the search api)

**Open Issues**
 1. Should there be a generator for the Discogs authority?

**Comment by zimeon** [comment]
Discussion in LD4P2 meeting is that we don't expect to be able to use a generator in this project, expect to need Javascript code that can be incorporated in BFE/Sinopia

**Comment by tworrall** [comment]
May tweak the way the Discogs key and secret are configured, but otherwise this is done.
