### ISSUE TITLE
Develop the translation module for the Discogs authority

### ISSUE THREAD

**Issue by tworrall** [LD4P/qa_server#35]
**Basic features**
 1. The module maps the Discogs' terms to their corresponding Bibframe properties (and URIs where relevant)
 2. The "show" URL returns JSON-LD

**Comment by zimeon** [comment]
Translations: https://github.com/LD4P/ld4p2-cornell/blob/master/Sinatra/Discogs/annotated_sinatra.json

**Comment by tworrall** [comment]
Examples of the current json-ld:

https://github.com/LD4P/ld4p2-cornell/wiki/Discogs-JSON-LD---N3-examples

**Comment by tworrall** [comment]
The Discogs tracklist data is now part of the JSON-LD that the translation module produces. The examples on the this wiki page have been updated to reflect that:

https://github.com/LD4P/ld4p2-cornell/wiki/Discogs-JSON-LD-and-N3-examples

Still need to finalize whether the work-level extra artists get associated with the tracks or stay with the work. @sfolsom to make this decision.

**Comment by tworrall** [comment]
For @sfolsom -- here are a couple of questions relating to roles.

1. The discogs artists are set up as agents:

:work1 bf:contribution :primaryContribution .
:primaryContribution bf:agent <artist uri> .

But we haven't set up roles for them. Should they have roles? (We did do that with the extra artists listed at the track level.)

2. When we do create roles, should we be using LoC relators? 

http://id.loc.gov/vocabulary/relators/collection_BIBFRAMEWork.html

**Comment by sfolsom** [comment]
Let's put artists on both albums and songs (primary contributions), and extra artists only on albums (contributions).

With roles, let's not worry about trying to map them to LoC relators and just use rdfs:labels off the Roles.

**Comment by tworrall** [comment]
The [JSON-LD and N3 examples](https://github.com/LD4P/ld4p2-cornell/wiki/Discogs-JSON-LD-and-N3-examples) reflect the coding changes made in response to (1) Steven's answers to the questions above and (2) his updates to the [annotated SInatra JSON file](https://github.com/LD4P/ld4p2-cornell/blob/master/Sinatra/Discogs/annotated_sinatra.json).

**Comment by tworrall** [comment]
Because the Discogs authority uses yaml files to map Discogs terms to LOC terms, need to write a generator class that copies these files to the root rails application.

**Comment by tworrall** [comment]
Looks like there may need to be updates to distinguish between masters and releases. If so, the changes to the code won't be that significant.

**Comment by tworrall** [comment]
1. Implemented subauthorities to handle masters and releases separately, while retaining the ability to return JSON-LD if no subauthority is specified.

2. New code to check if a release has a master. If it does, the primary information for the work being defined now comes from that master rather than the release.

3. In some instances a Discogs release and master can share the same ID. So if no subauthority is specified and the ID matches both a release and master, the Discogs authority returns a message to that effect. Otherwise it returns the data for whichever type matched the ID.

**Comment by tworrall** [comment]
Per Lynette's direction, refactored the code to follow the subauthority_for structure. As a result, had to add a third subauthority ("all"), modify some existing tests and add two new tests.

**Comment by tworrall** [comment]
The Discogs [pull request in QA](https://github.com/samvera/questioning_authority/pull/220) has been merged. Closing this issue.
