### ISSUE TITLE
New Indexing: Getty TGN - changes in accuracy tests

### ISSUE THREAD

**Issue by elrayle** [LD4P/qa_server#395]
The new indexing scheme has the following impact on GETTY_TGN accuracy tests:

![image](https://user-images.githubusercontent.com/6855473/101540463-0d76b000-396e-11eb-8c87-7027b9b2f34f.png)

See also Issue #414 which reports a similar issue for GETTY_ULAN  which expects `-agent` at the end of each subject URI.

**Comment by sfolsom** [comment]
@eichmann this is seems to be happening on your end. No (or odd results without labels in the case of Nile River) are showing up.

**Comment by elrayle** [comment]
These all fail because the subject URIs are real world object URIs that end in `-place`.

ACTION: @eichmann will adjust the index to return the correct type URIs.

**Comment by elrayle** [comment]
NOTE: ULAN is similar.  @sfolsom URIs need to be updated to the real world object version `-person`, `-place`, etc.

**Comment by sfolsom** [comment]
Correct suffix for URIs added: https://github.com/LD4P/qa_server/pull/410

**Comment by elrayle** [comment]
All green on the tests.  Thanks @eichmann!!!
