### ISSUE TITLE
New Indexing: LOCGENRES - changes in accuracy tests

### ISSUE THREAD

**Issue by elrayle** [LD4P/qa_server#397]
The new indexing scheme has the following impact on LOCGENRES accuracy tests:

All tests are passing except one, which was failing before the indexing change.  This issue is to explore and document why that one test continues to fail.

![image](https://user-images.githubusercontent.com/6855473/101542465-c8a04880-3970-11eb-8faa-40618e6d965e.png)

**Comment by sfolsom** [comment]
Cookery is a madsrdf:DeprecatedAuthority. We still want these to show up in the results because in most cases they point the heading that replaces it. See: https://docs.google.com/spreadsheets/d/1rPvEoP9iYNkxJ0eWC8gXe3ci7e6mhW0da59xkGhadi0/edit#gid=696491968

**Comment by elrayle** [comment]
It appears that the DeprecatedAuthority data is not included in the download.

ACTION: @sfolsom will contact LOC to see if they can include DeprecatedAuthority data in the download.

**Comment by elrayle** [comment]
Looking closer at this, it appears that when `cookery` was original in LCSH.  When it was deprecated with replacement `cookbook`, it was also moved to LCGFT.

ACTION: @sfolsom will think through the implications of this.

**Comment by elrayle** [comment]
From @sfolsom in Slack:
> Digging further, the Cookery test was written wrong, and the term actually brings up the desired entity within each dataset, so i deleted the test.

Removed in PR #415
