### ISSUE TITLE
Failing Connection Test: LOCNAMES_RWO_NEW_LD4L_CACHE/family q=twain

### ISSUE THREAD

**Issue by elrayle** [LD4P/qa_server#405]
### Browser Access for Test:  

https://lookup-int.ld4l.org/authorities/search/linked_data/locnames_rwo_new_ld4l_cache/family?q=twain&maxRecords=4&context=true

```
[]
```

The old indexing approach returns 4 results as expected: https://lookup-int.ld4l.org/authorities/search/linked_data/locnames_rwo_ld4l_cache/family?q=twain&maxRecords=4&context=true

### Monitor Status results in UI:

![image](https://user-images.githubusercontent.com/6855473/101813774-2d7fae00-3aeb-11eb-91bd-f9c03b95c5ca.png)

### CURL access directly to wintermute

```
$ curl -L -D - -H 'Accept: application/n-triples' 'http://wintermute.slis.uiowa.edu:8081/ld4l_services/loc_rwo_name_batch.jsp?query=twain&maxRecords=4&startRecord=1&entity=Family&lang=en'
HTTP/1.1 200 
Set-Cookie: JSESSIONID=00712B1DFA1751C791DF36CEB0CBDE4D;path=/ld4l_services;HttpOnly
Content-Type: application/n-triples;charset=UTF-8
Transfer-Encoding: chunked
Date: Thu, 10 Dec 2020 18:24:37 GMT

<http://ld4l.org/ld4l_services/cache> <http://vivoweb.org/ontology/core#count> "0" .
```

**Comment by elrayle** [comment]
ACTION: @eichmann will look at why 0 results are returned for Family.  Suspected that this subauthority has an issue.

**Comment by eichmann** [comment]
Twain is not a listed family. Waterman works fine on part 3 of your test suite.

**Comment by elrayle** [comment]
Looks like the test was updated to Waterman at some point.  So I think the test failure is resolved.

While looking at this, the test results are not showing labels.  This may be a configuration in how QA tries to extract the label.  I will look into this.
