### ISSUE TITLE
Extract labels from HTTP response headers

### ISSUE THREAD

**Issue by kirkhess** [LD4P/qa_server#45]
From http://id.loc.gov/techcenter/:

> Requesting a concept URI with a HTTP HEAD method exposes a private header called "X-PrefLabel", that is a URL-encoded representation of the preferred label.
> 
> For example, running cURL with the "-I" argument on the URI for "Bahia grass" performs a HTTP request using the HEAD method.
> 
> curl -I http://id.loc.gov/authorities/subjects/sh93007391
> HTTP HEAD requests return the HTTP response only, sans the body of the RDF or XHTML content. Among these headers, one would see a given header "X-PrefLabel: Bahia%20grass". It is possible to use a HTTP library within the programming language of your choice to access this header. URL-decoding the value of the X-PrefLabel header yields the string "Bahia grass".

The specific use case that should be considered is for MESH subjects, so they could be easily matched via the label to the X-URI.

**Comment by elrayle** [comment]
It's not clear what the use case for this would be in the current ecosystem of the cache-qa_normalization-sinopia_editor.  This can be reopened later if a use case becomes clear.  Thanks for bringing this information to our attention.  If you feel that this issue should remain open, please provide details on the use case that you see this fulfilling.
