### ISSUE TITLE
ingest and index ShareVDE CKB 2.0

### ISSUE THREAD

**Issue by elrayle** [LD4P/qa_server#455]
- [X] ingest
- [X] identify context to include (may need fuller evaluation; requires feedback to ShareVDE on issues; can be indexed now)
- [x] index
- [x] configure in QA
- [x] configure in Sinopia

Target Date: Oct 22, 2021

**Comment by sfolsom** [comment]
Some parts of the context in 2.0 remain the same, some queries need updating, and like last time, we have to talk to SVDE about mangled authority labels. https://docs.google.com/spreadsheets/d/1rPvEoP9iYNkxJ0eWC8gXe3ci7e6mhW0da59xkGhadi0/edit#gid=502967565

**Comment by sfolsom** [comment]
@eichmann in case it wasn't clear, we can update the context for /ckb_2_0_stage_A based on on the spreadsheet linked above when you're ready. The green needs no changes. Yellow needs changes. If I remember correctly, Red doesn't need changes (We expect to use the same LDPath, but want to check to see if your queries align)... but the data currently isn't pretty.

**Comment by eichmann** [comment]
should be ready to close this!
