### ISSUE TITLE
Cleanup Sinopia labels for OCLC subauths for direct and cache access

### ISSUE THREAD

**Issue by elrayle** [LD4P/qa_server#459]
This issue is described in detail in https://github.com/LD4P/sinopia_editor/issues/2125.  See that issue and record exploration results there.

**Comment by sfolsom** [comment]
Questions we need to answer can be found at the bottom of this spreadsheet: https://docs.google.com/spreadsheets/d/1baAgyP3CtmJ31fTGYzRcykUE1RSS126L8U8f0UI7zIo/edit?usp=sharing

**Comment by sfolsom** [comment]
Resolved with https://github.com/LD4P/sinopia_editor/commit/d1664cc7c52b845f0307cde859fdbb19cffa3034.
