### ISSUE TITLE
search doesn't always return the number of requested records

### ISSUE THREAD

**Issue by elrayle** [LD4P/qa_server#463]
### Returns too few 
(request 4, receive 3)
https://lookup.ld4l.org/authorities/search/linked_data/agrovoc_ld4l_cache?q=melon%20seed&maxRecords=4&context=false

Same query with larger request 
(request 5, receive 4)
https://lookup.ld4l.org/authorities/search/linked_data/agrovoc_ld4l_cache?q=melon%20seed&maxRecords=5&context=false

### Returns too many 
(request 4, receive 5)
https://lookup.ld4l.org/authorities/search/linked_data/locnames_rwo3_ld4l_cache/organization?q=ACLU&maxRecords=4

### Correct number 
includes an exact match
(request 4, receive 4) 
https://lookup.ld4l.org/authorities/search/linked_data/locnames_rwo3_ld4l_cache/organization?q=University%20of%20Pennsylvania&maxRecords=4

no exact match
(request 4, receive 4) 
https://lookup.ld4l.org/authorities/search/linked_data/locgenres_ld4l_cache?q=animation&maxRecords=4&context=false

**Comment by eichmann** [comment]
D.A.V.E. now counts properly...

**Comment by elrayle** [comment]
Looks good! Thanks
