### ISSUE TITLE
MeSH 

### ISSUE THREAD

**Issue by bushmanb** [LD4P/qa_server#47]
_Please only use this issue template for LD4P2 requests for a new data source to be added to QA. If your requesting changes to how a dataset currently available in QA is treated, please use the indexing bug issue template._

__For LD4P2 partners and cohorts:__

More information about making a request can be found at https://wiki.duraspace.org/display/LD4P2/Request+a+New+Dataset+For+QA

Please perform each task listed below. (Email sf433 @ cornell dot edu with questions):

- [x] Identify the data source: (Include the Data Source Name and its homepage URL)
- [x] Add a new tab and indexing information for the data source to the following spreadsheet: https://docs.google.com/spreadsheets/d/1rPvEoP9iYNkxJ0eWC8gXe3ci7e6mhW0da59xkGhadi0/edit?usp=sharing.

**MeSH RDF:  https://id.nlm.nih.gov/mesh/

Download via FTP: ftp://ftp.nlm.nih.gov/online/mesh/rdf/**

Next steps: 

A link to a YAML file will be shared with the requestor via a comment in the issue in order to complete the Accuracy Test portion of Writing Tests for an Authority. Edit directly the YAML file in Github, save. Create a Pull Request to be reviewed. Be sure to including a meaningful commit message (e.g. adding accuracy tests for Authority X).

_Please note, all requests for new data sources in QA will be prioritized by the LD4P2 project. Due to time restrictions there is no guarantee that all requests will be added to QA during the lifetime of the LD4P2 grant; regardless of resources it is still useful to know which datasets the community would find useful in such a lookup service._

**Comment by sfolsom** [comment]
@elrayle MESH is already in QA. Is there a placeholder YAML file that @bushmanb can add tests for?

**Comment by elrayle** [comment]
Accuracy tests can be added to...
[lib/generators/qa_server/templates/config/authorities/linked_data/scenarios/mesh_ld4l_cache_validation.yml](https://github.com/LD4P/qa_server/blob/master/lib/generators/qa_server/templates/config/authorities/linked_data/scenarios/mesh_ld4l_cache_validation.yml)

**Comment by elrayle** [comment]
- [ ] owner - @sfolsom is working on getting someone to own this
- [x] data in D.A.V.E
- [x] configured in QA
  - [x] basic term and search configuration
  - [ ] subauthority configuration - pending info from @eichmann about whether there are any subauthorities
- [x] connection tests
  - [x] basic term and search test 
    - [x] written
    - [x] on production server
  - [ ] subauthority connection tests
    - [ ] written
    - [ ] on production server
- [ ] accuracy tests
    - [ ] written
    - [ ] on production server
    - [ ] passing

**Comment by elrayle** [comment]
@eichmann will reach out to @bushmanb to determine what updates are needed for the index and what data should be in the results sent to QA.

**Comment by sfolsom** [comment]
@eichmann where do we stand with indexing MESH from NLM, rather than BioPortal: ftp://nlmpubs.nlm.nih.gov/online/mesh/rdf/2018/ rather than http://bioportal.bioontology.org/?

**Comment by eichmann** [comment]
@sfolsom triple stores are updated to current (Apr 2019).  Now the crux of the biscuit - we have concepts with labels and preferred terms, and terms with preferred labels. Should I use concepts or terms as the URIs of interest?

**Comment by bushmanb** [comment]
@eichmann We would want the URIs for the preferred concepts.  Thanks.

**Comment by eichmann** [comment]
Note also that vocab#Descriptor does not appear in the data...

**Comment by eichmann** [comment]
Hence
<http://id.nlm.nih.gov/mesh/C000002>    <http://id.nlm.nih.gov/mesh/vocab#preferredConcept>     <http://id.nlm.nih.gov/mesh/M0040005>

means I index M0040005, correct?

**Comment by bushmanb** [comment]
I am not sure why vocab#Descriptor is not appearing the data.  That is why at want. We only want URIs that contain D numbers.  We do not want URIs with C numbers or M numbers.

**Comment by danizen** [comment]
> Note also that vocab#Descriptor does not appear in the data...

This is correct.   Our vocabulary says that `meshv:TopicalDescriptor` is a subclass of `meshv:Descriptor`, likewise `meshv:GeographicalDescriptor` and `meshv:PublicationType`.   This is covered on our documentation page about descriptors.

If you index each of these, great, but this does raise the question about how you can find them in a single query, without inference, without the performance impact and basic support questions that raises.
The answer is to use a UNION query, for example:

```
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX meshv: <http://id.nlm.nih.gov/mesh/vocab#>
PREFIX mesh: <http://id.nlm.nih.gov/mesh/>

SELECT ?descriptor ?label
FROM <http://id.nlm.nih.gov/mesh>
WHERE {
  { ?descriptor a meshv:TopicalDescriptor } 
  UNION { ?descriptor a meshv:GeographicalDescriptor }
  UNION { ?descriptor a meshv:PublicationType } .    
  ?descriptor rdfs:label ?label .
} ORDER BY ?label
```

Another problem with our [downloads](ftp://ftp.nlm.nih.gov/online/mesh/rdf/) is that some "obsolote" aka "inactive" descriptors are included.   I would recommend using some mechanism to remove in active resources from the triple store after loading mesh.nt.gz, or indexing their inactive/active state along with their label and URI:

```
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX meshv: <http://id.nlm.nih.gov/mesh/vocab#>
PREFIX mesh: <http://id.nlm.nih.gov/mesh/>

SELECT ?descriptor ?label ?active
FROM <http://id.nlm.nih.gov/mesh>
WHERE {
  { ?descriptor a meshv:TopicalDescriptor } 
  UNION { ?descriptor a meshv:GeographicalDescriptor }
  UNION { ?descriptor a meshv:PublicationType } .    
  ?descriptor rdfs:label ?label .
  ?descriptor meshv:active ?active .  
} ORDER BY ?label
```

Active is an xsd:boolean, so you can also just suggest that the RDF solution is only for meshv:active "true"^^xsd:boolean

FYI - @bushmanb asked me to hop on-board as a technical guy maintaining MeSH RDF. Let me know whether this works for you or if you still have questions.

**Comment by sfolsom** [comment]
Yes, sorry about this @eichmann. (I thought I had a note in the spreadsheet about having to query for subclasses of meshv:Descriptor, but I don't see it there anymore.

@danizen, thanks for the note about inactives. Is this a case where the inactives are deprecated and point to something that replaces them? If so, we can follow a pattern we're attempting with madsrdf:DeprecatedAuthority resources in LCGFT, to index and point to their replacements.

**Comment by danizen** [comment]
> Is this a case where the inactives are deprecated and point to something that replaces them?
> If so, we can follow a pattern we're attempting with madsrdf:DeprecatedAuthority resources
> in LCGFT, to index and point to their replacements.

Sometimes it is reasonable to figure out the new descriptor, using the magic reasoning powers of RDF.
Consider the "Fate of deleted descriptors" download from What's [New?](https://www.nlm.nih.gov/mesh/whatsnew.html)

9 descriptors are retired, and unsurprisingly, [this query ](https://id.nlm.nih.gov/mesh/query?query=PREFIX+rdf%3A+%3Chttp%3A%2F%2Fwww.w3.org%2F1999%2F02%2F22-rdf-syntax-ns%23%3E%0D%0APREFIX+rdfs%3A+%3Chttp%3A%2F%2Fwww.w3.org%2F2000%2F01%2Frdf-schema%23%3E%0D%0APREFIX+xsd%3A+%3Chttp%3A%2F%2Fwww.w3.org%2F2001%2FXMLSchema%23%3E%0D%0APREFIX+owl%3A+%3Chttp%3A%2F%2Fwww.w3.org%2F2002%2F07%2Fowl%23%3E%0D%0APREFIX+meshv%3A+%3Chttp%3A%2F%2Fid.nlm.nih.gov%2Fmesh%2Fvocab%23%3E%0D%0APREFIX+mesh%3A+%3Chttp%3A%2F%2Fid.nlm.nih.gov%2Fmesh%2F%3E%0D%0APREFIX+mesh2019%3A+%3Chttp%3A%2F%2Fid.nlm.nih.gov%2Fmesh%2F2019%2F%3E%0D%0APREFIX+mesh2018%3A+%3Chttp%3A%2F%2Fid.nlm.nih.gov%2Fmesh%2F2018%2F%3E%0D%0APREFIX+mesh2017%3A+%3Chttp%3A%2F%2Fid.nlm.nih.gov%2Fmesh%2F2017%2F%3E%0D%0A%0D%0ASELECT+%3FpriorDescriptor+%3FpriorLabel%0D%0AFROM+%3Chttp%3A%2F%2Fid.nlm.nih.gov%2Fmesh%3E%0D%0AWHERE+%7B%0D%0A++%3FpriorDescriptor+a+meshv%3ADescriptor+.%0D%0A++%3FpriorDescriptor+meshv%3Aactive+%22false%22%5E%5Exsd%3Aboolean+.%0D%0A++%3FpriorDescriptor+meshv%3AlastActiveYear+%222018%22%40en+.%0D%0A++%3FpriorDescriptor+meshv%3ApreferredConcept+%3FpriorConcept+.%0D%0A++%3FpriorConcept+rdfs%3Alabel+%3FpriorLabel+.%0D%0A%7D%0D%0A&format=HTML&inference=true&year=current&limit=50&offset=0#lodestart-sparql-results) returns them.

However, many of their old preferred concepts are also retired.   For those concepts that are live, we can see which active descriptor currently holds that concept, with [this query](https://id.nlm.nih.gov/mesh/query?query=PREFIX+rdf%3A+%3Chttp%3A%2F%2Fwww.w3.org%2F1999%2F02%2F22-rdf-syntax-ns%23%3E%0D%0APREFIX+rdfs%3A+%3Chttp%3A%2F%2Fwww.w3.org%2F2000%2F01%2Frdf-schema%23%3E%0D%0APREFIX+xsd%3A+%3Chttp%3A%2F%2Fwww.w3.org%2F2001%2FXMLSchema%23%3E%0D%0APREFIX+owl%3A+%3Chttp%3A%2F%2Fwww.w3.org%2F2002%2F07%2Fowl%23%3E%0D%0APREFIX+meshv%3A+%3Chttp%3A%2F%2Fid.nlm.nih.gov%2Fmesh%2Fvocab%23%3E%0D%0APREFIX+mesh%3A+%3Chttp%3A%2F%2Fid.nlm.nih.gov%2Fmesh%2F%3E%0D%0A%0D%0ASELECT+%3FpriorDescriptor+%3FpriorLabel+%3FnewDescriptor+%3FnewLabel%0D%0AFROM+%3Chttp%3A%2F%2Fid.nlm.nih.gov%2Fmesh%3E%0D%0AWHERE+%7B%0D%0A++%3FpriorDescriptor+a+meshv%3ADescriptor+.%0D%0A++%3FpriorDescriptor+meshv%3Aactive+%22false%22%5E%5Exsd%3Aboolean+.%0D%0A++%3FpriorDescriptor+meshv%3AlastActiveYear+%222018%22%40en+.%0D%0A++%3FpriorDescriptor+meshv%3ApreferredConcept+%3FpriorConcept+.%0D%0A++%3FpriorConcept+rdfs%3Alabel+%3FpriorLabel+.%0D%0A++%3FnewDescriptor+a+meshv%3ADescriptor+.%0D%0A++%3FnewDescriptor+meshv%3Aactive+%22true%22%5E%5Exsd%3Aboolean+.%0D%0A++%3FnewDescriptor+meshv%3Aconcept+%3FpriorConcept+.%0D%0A++%3FnewDescriptor+rdfs%3Alabel+%3FnewLabel+.%0D%0A%7D%0D%0A&format=HTML&inference=true&year=current&limit=50&offset=0#lodestart-sparql-results).

Now, these queries can be adjusted to work without inference, and the current graph is only about 15 million triples, so you should be able to do this well with TDB, poorly with rdflib or something like that.

My guess is that in practice it might even be easier to locate the prior years' "Fate of missing Descriptors" documents and then use a PDF parser library to find them all.   Not RDF, but it is something.

**Comment by danizen** [comment]
If you are interested also in representing hierarchy, consider `meshv:broaderDescriptor` over the MeSH tree.   The mesh tree is a pure tree, and represents to some extent "dimensions" such as in SNOMED CT, but it also is true that a single descriptor can have multiple tree numbers.

If you use `meshv:broaderDescriptor`, you have what is I think a simpler problem - it is not a pure hierarchy, you may have a single MeSH descriptor with several broader descriptors.

**Comment by elrayle** [comment]
@danizen When we were using BioPortal, we used the following for broader and narrower.  I'm wondering what they should be now.  I saw that you mentioned `meshv:broaderDescriptor` for broader terms.  Is there an equivalent for narrower?

For bioportal...
```
      "broader_ldpath":  "bmesh:mapped_to ::xsd:anyURI",
      "narrower_ldpath": "bmesh:mapped_from ::xsd:anyURI"
```

Proposed for NLM...
```
      "broader_ldpath":  "meshv:broaderDescriptor ::xsd:anyURI",
      "narrower_ldpath": "meshv:??? ::xsd:anyURI"
```

**Comment by elrayle** [comment]
@danizen Looking at the data, there is a narrowerConcept and broaderConcept.  How do those fit into this discussion?

**Comment by bushmanb** [comment]
There is no equivalent for narrower.  We only have the predicate meshv:broaderDescriptor.  You should be able to use inference to retrieve all narrower terms.

Thanks,
Barbara

**Comment by bushmanb** [comment]
For cataloging purposes, the concepts are only used see references to the main descriptor.  We do not care if they are broader or narrower concepts to other concepts.

Thanks,
Barbara

**Comment by danizen** [comment]
for concepts, there is a concept of narrower, e.g. the concepts form a forest.    However, for descriptors, the "children" of the descriptor actually depend not just on the parent descriptor, but on its grandparent, and so on, e.g. the entire path of descriptors up to that point.  [The documentation](https://hhs.github.io/meshrdf/tree-numbers)  has a good demonstration of why this might be so.

And this is reflected in the meshv:TreeNumber rdfs class.   A meshv:TreeNumber instance represents a path of meshv:Descriptor instances from the root. 

You can see "Eye" in BioPortal as well - https://bioportal.bioontology.org/ontologies/MESH?p=classes&conceptid=http%3A%2F%2Fpurl.bioontology.org%2Fontology%2FMESH%2FD005123.  It reflects this in that "Eye" is both a subClassOf "Face" and "Sense Organs".   And so, if you use straight "subClassOf" relationships you have the surprising result that the "Photoreceptor Cells" are also a subClassOf of both "Sense Organs" and "Face".

So here, we can see that the representation in BioPortal uses semantic web technologies in a way that actually distorts the semantics of these terms in medicine.

**Comment by eichmann** [comment]
So, summarizing this thread from the perspective of what I use to generate the index (and avoiding for now the nuances of descriptor broader/narrower semantics:

- Grab a descriptor (using @danizen's union scheme for Descriptor subclasses)
- snag the descriptor's preferredConcept and the pC's preferredTerm
- snag the pC's other Terms

then the "document" in Lucene is

- descriptor URI
- preferredTerm's label to be used to present results
- content bucket is the preferredTerm label and all other Term labels

Let's see what the search results look like and proceed from there?

**Comment by eichmann** [comment]
`PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX meshv: <http://id.nlm.nih.gov/mesh/vocab#>
PREFIX mesh: <http://id.nlm.nih.gov/mesh/>

SELECT ?descriptor ?pc ?pt ?label 
WHERE {
  { ?descriptor a meshv:TopicalDescriptor } 
  UNION { ?descriptor a meshv:GeographicalDescriptor }
  UNION { ?descriptor a meshv:PublicationType } .    
  ?descriptor meshv:preferredConcept ?pc .
  ?pc meshv:preferredTerm ?pt .
  ?pt meshv:prefLabel ?label .
} limit 10`

**Comment by eichmann** [comment]
This gets us the target URI and a label.  Subsequent query would pick up the non-preferred Term labels.  Should we also include the altLabels present for terms?

**Comment by eichmann** [comment]
scopeNotes of any utility as well?

**Comment by danizen** [comment]
@eichmann, I asked the same question when trying to find all terms for a descriptor for the backend interfaces of NLM Classification, which is also focused on Library IT, and I was told that I didn't need the altLabel.   

A descriptor may also have zero or more meshv:seeAlso object properties that relate that descriptor to other descriptors.

**Comment by bushmanb** [comment]
@danizen is correct, we do not need the altLabels present for the terms, but scopeNotes and annotation are needed.

**Comment by danizen** [comment]
@eichmann, I'm working on some RESTful APIs that will help, but you may wish to do it using our SPARQL endpoint anyway.  

Also, If you want to collect all descriptors, I can provide a useful algorithm using meshv:broaderDescriptor to descend the hierarchy.

**Comment by sfolsom** [comment]
I've updated the MESH Context information based on comments above and the move to LDPath for describing desired context, https://docs.google.com/spreadsheets/d/1rPvEoP9iYNkxJ0eWC8gXe3ci7e6mhW0da59xkGhadi0/edit#gid=2113261477 (@eichmann note that you can simplify the prefLabel queries by using the rdfs:labels on meshv:AllowedDescriptorQualifierPair and  meshv:Descriptor individuals.)

**Comment by sfolsom** [comment]
Accidentally made a new issue for LDPath: https://github.com/LD4P/qa_server/issues/117

**Comment by michelleif** [comment]
from Barbara Bushman on slack august 22nd:
Not exactly sure if this will help with the QA tool, but we just released a Lookup Service API for MeSH at https://id.nlm.nih.gov/mesh/lookup/

**Comment by elrayle** [comment]
It looks to me like this issue is complete.  @bushmanb Can you confirm?  My last reading of this issue was the request for narrower terms.  I confirmed that they are included in the extended context at...

https://lookup.ld4l.org/authorities/search/linked_data/mesh_nlm_ld4l_cache/subject?q=Heart%20Attack&maxRecords=5&context=true

**Comment by bushmanb** [comment]
@elrayle I agree that I see the narrower terms in the data and this is complete.
