### ISSUE TITLE
New dataset: NTSF - Norwegian thesaurus on genre and form

### ISSUE THREAD

**Issue by danmichaelo** [LD4P/qa_server#481]
At Oslo University Library and Biblioteksentralen (Norwegian Library Center), we're exploring the use of Sinopia for cataloguing. Following up from a meeting with Michelle Futornick in December ([minutes](https://docs.google.com/document/d/1b7eM0UBkU2MVdZsWtXwHpV0UmV2w-uBNq7wCAj2pj2k/)), we would like to request a few Norwegian vocabularies to be added to QA.

First out is NTSF, an authority register for form and genre terms, which is mostly aligned with LCGFT. The vocabulary has a quite simple structure with only a single concept type and only standard SKOS relations.

- [x] Consult https://github.com/LD4P/qa_server/wiki/Authority-Lookup-Support-Plan-for-Sinopia to confirm that the dataset isn't already supported.
- [x] Identify the data source: (Include the Data Source Name, its homepage URL, and any relevant API and/or download information to aid in caching.):

  - Data Source Name: 
      - Norwegian Bokmål (nb): `Norsk tesaurus for sjanger og form`
      - Norwegian Nynorsk (nn): `Norsk tesaurus for sjanger og form`
      - English (en): `Norwegian thesaurus on genre and form`
      - Code: `NTSF`
  - Homepage: https://www.nb.no/nbvok/ntsf/
  - Data dump (Turtle): https://www.nb.no/nbvok/rest/v1/ntsf/data?format=text/turtle  
  - REST API (Skosmos): https://nb.no/nbvok/rest/v1/ntsf/search

- [ ] Add a new tab for the data source to https://docs.google.com/spreadsheets/d/1rPvEoP9iYNkxJ0eWC8gXe3ci7e6mhW0da59xkGhadi0/edit?usp=sharing
     - Status: Pending access request

- [x] Draft configuration file: https://github.com/biblioteksentralen/sinopia_qa_server_config/blob/main/authorities/linked_data/ntsf_direct.json - I'm not sure about all the different options, for instance the practical implications of `drillable`, but hope it's still useful as a starting point.

- [x] Basic accuracy tests: https://github.com/biblioteksentralen/sinopia_qa_server_config/blob/main/authorities/linked_data/scenarios/ntsf_direct_validation.yml - I've only created one test so far since the vocabulary is quite basic. There is only one concept type (skos:Concept), so testing different subauthorities is not needed. Do you still think there should be more tests?

I will update this issue once I've been able to add the necessary information to the Google Docs spreadsheet.

**Comment by sfolsom** [comment]
@danmichaelo sorry for the delay getting you access to the spreadsheets. You should be able to edit it now. Once we have a tab for this dataset, we should be able to proceed.

**Comment by elrayle** [comment]
@danmichaelo You did an excellent job putting together the config and validation.  I wish I hadn't missed that the request was pending.  I could have put this in to production sooner.  I tested this out and everything works great.  I'll put it into production shortly and let you know when it is available for use in Sinopia.

Testing results:
![image](https://user-images.githubusercontent.com/6855473/161121508-fa29f786-1deb-495b-a8f4-55c8ad177785.png)

**Comment by danmichaelo** [comment]
> @danmichaelo You did an excellent job putting together the config and validation. I wish I hadn't missed that the request was pending. I could have put this in to production sooner. I tested this out and everything works great. I'll put it into production shortly and let you know when it is available for use in Sinopia.

Thanks @elrayle ! Bibbi authorities (#482) works great now, but NTSF (Norwegian thesaurus on genre and form) unfortunately does not. It returns results from Bibbi, so it seems like there's been a mix-up:

https://lookup.ld4l.org/authorities/search/linked_data/ntsf_direct?q=roman&maxRecords=10&lang=en&context=true&response_header=true&startRecord=1

Also note that it's not called "Norwegian thesaurus", but "Norwegian thesaurus on genre and form". It's a specialized form/genre vocabulary.

**Comment by elrayle** [comment]
@danmichaelo I accidentally copied the Bibbi config into NTSF.  This is fixed by PR https://github.com/cul-it/qa_server/pull/344.

The name of the authority, as it appears in Sinopia, is fixed in PR https://github.com/LD4P/sinopia_editor/pull/3516
