### ISSUE TITLE
New dataset: Bibbi authorities

### ISSUE THREAD

**Issue by danmichaelo** [LD4P/qa_server#482]
At Oslo University Library and Biblioteksentralen (Norwegian Library Center), we're exploring the use of Sinopia for cataloguing. Following up from a meeting with Michelle Futornick in December ([minutes](https://docs.google.com/document/d/1b7eM0UBkU2MVdZsWtXwHpV0UmV2w-uBNq7wCAj2pj2k/)), we would like to request a few Norwegian vocabularies to be added to QA.

Bibbi authorities is an integrated authority register for the authorities from Biblioteksentralen. The vocabulary is available as SKOS and has a few different concept types.

- [x] Consult https://github.com/LD4P/qa_server/wiki/Authority-Lookup-Support-Plan-for-Sinopia to confirm that the dataset isn't already supported.
- [ ] Identify the data source: (Include the Data Source Name, its homepage URL, and any relevant API and/or download information to aid in caching.):

  - Data Source Name: 
      - Norwegian Bokmål (nb): `Bibbi autoriteter`
      - Norwegian Nynorsk (nn): `Bibbi autoritetar`
      - English (en): `Bibbi authorities`
      - Code: `BIBBI`
  - Homepage: https://vokabular.bs.no/bibbi/
  - Data dump (Turtle): TODO
  - REST API (Skosmos): https://vokabular.bs.no/rest/v1/bibbi/search

- [ ] Add a new tab for the data source to https://docs.google.com/spreadsheets/d/1rPvEoP9iYNkxJ0eWC8gXe3ci7e6mhW0da59xkGhadi0/edit?usp=sharing
     - Status: Pending access request

- [x] Draft configuration file (starting point): https://github.com/biblioteksentralen/sinopia_qa_server_config/blob/main/authorities/linked_data/bibbi_direct.json

- [x] Basic accuracy tests: https://github.com/biblioteksentralen/sinopia_qa_server_config/blob/main/authorities/linked_data/scenarios/bibbi_direct_validation.yml

I will update this issue once I've been able to add the necessary information to the Google Docs spreadsheet.

**Comment by sfolsom** [comment]
@danmichaelo is there a timeline for when this dataset might have a data dump? It's much easier for us to add new datasets as lookups if we cache the data locally.
