### ISSUE TITLE
New dataset: Humord

### ISSUE THREAD

**Issue by danmichaelo** [LD4P/qa_server#483]
Following the inclusion of #481 and #482 (thanks, @elrayle !), we would like to include a third Norwegian vocabulary: Humord 

Humord is an integrated authority register for the authorities from the University of Oslo Library. The vocabulary is available as SKOS.

- [x] Consult https://github.com/LD4P/qa_server/wiki/Authority-Lookup-Support-Plan-for-Sinopia to confirm that the dataset isn't already supported.
- [x] Identify the data source: (Include the Data Source Name, its homepage URL, and any relevant API and/or download information to aid in caching.):

  - Data Source Name: 
      - Norwegian Bokmål (nb): `Humord`
      - Norwegian Nynorsk (nn): `Humord`
      - English (en): `Humord`
      - Code: `HUMORD`
  - Homepage: https://data.ub.uio.no/skosmos/humord/nb/
  - Data dump (Turtle): http://data.ub.uio.no/dumps/humord.ttl
  - REST API (Skosmos): https://data.ub.uio.no/skosmos/rest/v1/humord/search

- [ ] Add a new tab for the data source to https://docs.google.com/spreadsheets/d/1rPvEoP9iYNkxJ0eWC8gXe3ci7e6mhW0da59xkGhadi0/edit?usp=sharing
  - pending access (trying again with another account)

- [x] Draft configuration file (starting point): https://github.com/biblioteksentralen/sinopia_qa_server_config/blob/main/authorities/linked_data/humord_direct.json

- [x] Basic accuracy tests: https://github.com/biblioteksentralen/sinopia_qa_server_config/blob/main/authorities/linked_data/scenarios/humord_direct_validation.yml

    - Note: I don't get the subauthority tests to pass. Could it be because # is not escaped in type? Here's a working search for the *geographic* entity Ålesund: https://data.ub.uio.no/skosmos/rest/v1/humord/search?lang=nb&labellang=nb&maxhits=10&query=%C3%85lesund&type=http://data.ub.uio.no/onto%23Geographic

**Comment by elrayle** [comment]
Fixed by PRs https://github.com/cul-it/qa_server/pull/345 and https://github.com/LD4P/sinopia_editor/pull/3516

**Comment by elrayle** [comment]
From @danmichaelo...
> I do not yet see the changes at https://stage.sinopia.io/ , will they also be available there?

![image](https://user-images.githubusercontent.com/6855473/162736179-ff30715d-25d5-4686-a092-0ad29608d245.png)

**Comment by elrayle** [comment]
@danmichaelo PR https://github.com/LD4P/sinopia_editor/pull/3516 was merged 4 days ago, so I would expect it to update. @jermnelson Do you know when this will be available on Sinopia?  This is the fix of Norwegian thesaurus and the addition of Humord.

**Comment by jermnelson** [comment]
@elrayle this change is being deployed to all Sinopia environments.
