### ISSUE TITLE
Create list of cache lookups to remove and direct lookups to create

### ISSUE THREAD

**Issue by sfolsom** [LD4P/qa_server#496]
Using the usage information provided by Dave and the lists of important lookups for Sinopia stakeholders, create a list of cached lookup to remove and direct lookups to create.

Make clear:
- Lookups that will completely go away (can be deleted right now because they are not being used and haven't been identified as important to stakeholder group.)
- Cached lookups needing a direct replacement.

https://docs.google.com/spreadsheets/d/1J0r3oujeQKmcQzODBLvab19GTXocCDjqN_Pck2ORHFs/edit?usp=sharing

**Comment by zimeon** [comment]
Handled in https://github.com/cul-it/qa_server/projects/2
