### ISSUE TITLE
Add Lookup Config details to authorities list

### ISSUE THREAD

**Issue by jgreben** [LD4P/qa_server#51]
sinopia_editor and sinopia_profile_editor currently use separate local copies of a hand-coded json file in order to lookup the QA authority details from a urn string that originates from a resource template, e.g. given a uri `urn:ld4p:qa:oclc_fast:personal_name` in a resource template, we get back this from the json config:
```
{
    "label": "OCLCFAST personal_name (QA)",
    "uri": "urn:ld4p:qa:oclc_fast:personal_name",
    "authority": "oclc_fast",
    "subauthority": "personal_name",
    "language": "en",
    "component": "lookup"
  }
```
sinopia_editor then use the authority, sub-authority, language, and component values to construct the right kind of QA query using the appropriate react component.

Please expand the authorities short list at https://lookup.ld4l.org/authorities/list/linked_data/authorities to include the above details if given a specific parameter (e.g. ?details=true). The goal is to have a config that is automatically updated as new authorities are added to qa_server, and that can be retrieved easily by other individuals or services from this single endpoint.

Thanks!

**Comment by elrayle** [comment]
@jgreben Based on your example, it looks like this will include an entry per subauthority?  Can you confirm?

```
{
    "label": "OCLCFAST personal_name (QA)",
    "uri": "urn:ld4p:qa:oclc_fast:personal_name",
    "authority": "oclc_fast",
    "subauthority": "personal_name",
    "language": "en",
    "component": "lookup"
  },
{
    "label": "OCLCFAST corporate_name (QA)",
    "uri": "urn:ld4p:qa:oclc_fast:corporate_name",
    "authority": "oclc_fast",
    "subauthority": "corportate_name",
    "language": "en",
    "component": "lookup"
  }
```

My only question of the data shown is for the uri.  That looks like an internal id for sinopia profiles.  Is that correct?  I wouldn't really have an easy way to insert that.

**Comment by jgreben** [comment]
Hi @elrayle Yes, the way I coded it was to make a distinct entry for each subauthority, but we could entertain the idea of a more nested JSON doc. Any thoughts on that? 

The URI/URN gets automatically inserted into the template based on whatever ends up in this config doc, so the auth lookup config will be the originating source of this info. That being the case, can you generate one based on the pattern: `urn:ld4p:qa:{authority}:{subauthority}`?

All of the QA authority sources are lookup components, so in that case perhaps it is outside the scope of the short list to provide this info and sinopia can infer this based on the uri? For example, if the uri begins with `urn:ld4p:qa` we assume it is a lookup...

**Comment by elrayle** [comment]
Solution: 
* uri will be structured as: `"uri": "urn:qa:oclcfast_ld4l_cache:personal_name"`
* component will be dropped

**Comment by elrayle** [comment]
@jgreben This is what I am actually producing...

**Term with no subauthorities OR fetching term across subauthorities**
```
{
  "label":"oclc_fast term (QA)",
  "uri":"urn:qa:term:oclc_fast",
  "authority":"oclc_fast",
  "action":"term",
  "language":["en"]
},
```

**Search across subauthorities**
```
{
  "label":"oclc_fast search (QA)",
  "uri":"urn:qa:search:oclc_fast",
  "authority":"oclc_fast",
  "action":"search",
  "language":["en"]
},
```

**Search within a subauthority**
```
{
  "label":"oclc_fast search topic (QA)",
  "uri":"urn:qa:search:oclc_fast:topic",
  "authority":"oclc_fast",
  "subauthority":"topic",
  "action":"search",
  "language":["en"]
},
```

NOTES ON LANGUAGE: 
* QA supports requests for results to be returned in multiple languages, so the language is an array.  * The language shown is what is configured in the authority. If not configured in the authority, it is the site default language.  
* The language does NOT specify what the authority defines as supported languages.  That information is not configured in QA authorities.information.
* A user (defined as the caller, which in this case is Sinopia) can request an alternate language by setting accept_language in the request header or by passing in the language in the `lang` parameter of the QA request URL.

**Comment by jgreben** [comment]
Thanks @elrayle Looks good! We can use the "search" action as the key to specify that the QA lookup component should be used for that authority. 

The editor does not currently support the ability to set the accept_language in the request, but I created issue https://github.com/LD4P/sinopia_editor/issues/494 for that work to be done.
