### ISSUE TITLE
Request Ligatus' Language of Bindings

### ISSUE THREAD

**Issue by gracianipicardo** [LD4P/qa_server#63]
_Please only use this issue template for LD4P2 requests for a new data source to be added to QA. If your requesting changes to how a dataset currently available in QA is treated, please use the indexing bug issue template._

__For LD4P2 partners and cohorts:__

More information about making a request can be found at https://wiki.duraspace.org/display/LD4P2/Request+a+New+Dataset+For+QA

Please perform each task listed below. (Email sf433 @ cornell dot edu with questions):

- [x] Identify the data source: (Include the Data Source Name and its homepage URL)
**Ligatus' Language of Bindings**
URL - *https://www.ligatus.org.uk/lob/*
SPARQL endpoint - *http://data.ligatus.org.uk/sparql*

- [x] Add a new tab and indexing information for the data source to the following spreadsheet: https://docs.google.com/spreadsheets/d/1rPvEoP9iYNkxJ0eWC8gXe3ci7e6mhW0da59xkGhadi0/edit?usp=sharing.

Next steps: 

- [ ] A link to a YAML file will be shared with the requestor via a comment in the issue in order to complete the Accuracy Test portion of Writing Tests for an Authority. Edit directly the YAML file in Github, save. Create a Pull Request to be reviewed. Be sure to including a meaningful commit message (e.g. adding accuracy tests for Authority X).

_Please note, all requests for new data sources in QA will be prioritized by the LD4P2 project. Due to time restrictions there is no guarantee that all requests will be added to QA during the lifetime of the LD4P2 grant; regardless of resources it is still useful to know which datasets the community would find useful in such a lookup service._

**Comment by sfolsom** [comment]
@gracianipicardo do you know if Ligatus has a download?

**Comment by gracianipicardo** [comment]
I don't think so @sfolsom, but I'll reach out to them. Maybe they can provide a data dump.

**Comment by eichmann** [comment]
@gracianipicardo @sfolsom a Ligatus triplestore is now available for SPARQLing at http://services.ld4l.org/fuseki/dataset.html?tab=query&ds=/Ligatus - this is a screen scrape of the Turtle links off their website.  The SPARQL endpoint is not configured properly, and returns triplestore configuration triples, rather than data triples...

**Comment by eichmann** [comment]
@gracianipicardo @sfolsom As per Paloma's email from a few minutes ago, I've loaded the "official" dump file and deployed it.  It appears equivalent, but just to be on the safe side...

**Comment by elrayle** [comment]
Closing... Ligatus is on production all the way through to Sinopia
