### ISSUE TITLE
weight exact match higher than match + additional text

### ISSUE THREAD

**Issue by elrayle** [LD4P/qa_server#70]
DAVE indexing needs to be tweaked to weight exact matches heavier than a match that is a match + additional text (e.g. “Twain, Mark, 1835-1910” ranks higher then “Twain, Mark, 1845-1910 (Spirit)“)

https://lookup.ld4l.org/authorities/search/linked_data/locnames_ld4l_cache/person?q=Twain,%20Mark,%201835-1910&maxRecords=2

This issue applies to all authorities.

**Comment by elrayle** [comment]
From @eichmann...

> Run the exact match sparql query - if a hit, give it rank one, and count from there with the existing scheme

**Comment by eichmann** [comment]
loc_rwo_name_batch2.jsp with standard arguments has exact match search logic and is ready for testing.

**Comment by eichmann** [comment]
Version 2 (exact match) deployed on services.ld4l.org for testing:
- [ ] agrovoc_batch.jsp
- [ ] dbpedia_batch.jsp
- [ ] dbpedia_name_batch.jsp
- [ ] fast_batch.jsp
- [ ] geonames_batch.jsp
- [ ] getty_batch.jsp
- [ ] loc_demographics_batch.jsp
- [ ] loc_genre_batch.jsp
- [ ] loc_instance_batch.jsp
- [ ] loc_name_batch.jsp
- [ ] loc_performance_batch.jsp
- [ ] loc_rwo_name_batch.jsp
- [ ] loc_subject_batch.jsp
- [ ] loc_work_batch.jsp
- [ ] mesh_batch.jsp
- [ ] nalt_batch.jsp

**Comment by elrayle** [comment]
Tested this using the batch2 jsps on 3 authorities and all looked good.  

@eichmann This are ready to go live.  When you switch everything from batch2 to batch jsp, feel free to close this issue as fixed.

**Comment by eichmann** [comment]
xxx_batch2.jsp files have been mapped to xxx_batch.jsp
