### ISSUE TITLE
Update Context Spreadsheet to account for SVDE Data

### ISSUE THREAD

**Issue by sfolsom** [LD4P/qa_server#72]
Without decisions about what subauthorities, labels to search and display, and other context, SVDE data is going to be poorly represented in Sinopia. Will do a first pass of LDPath, etc. in https://docs.google.com/spreadsheets/d/1rPvEoP9iYNkxJ0eWC8gXe3ci7e6mhW0da59xkGhadi0/edit#gid=502967565 that can be tweaked by the cohort when needed. Probably needs yaml tests too...

**Comment by sfolsom** [comment]
@elrayle  can you confirm if the syntax “bf:carrier / skos:prefLabel | bf:carrier / rdfs:label” is going to work for QA? (it combines / and | so I'm guessing it'll be ok)

**Comment by sfolsom** [comment]
@elrayle @eichmann Also how can we get skos:prefLabels off of resources like <http://rdaregistry.info/termList/RDAContentType/1020> when SVDE links to them, but the labels aren't in the RDF? ... do we need to harvest the RDF from http://rdaregistry.info/termList/RDAContentType?

**Comment by elrayle** [comment]
(bf:carrier/skos:prefLabel) | (bf:carrier/rdfs:label)

**Comment by elrayle** [comment]
For QA to access them, the triple has to be in the extended graph I get from the cache system.  I leave it to @eichmann to comment on the feasibility of getting that data into the extended graph.

**Comment by sfolsom** [comment]
First pass complete. Needs feedback from folks expecting to use SVDE data.

**Comment by sfolsom** [comment]
@eichmann I've made changes to the LDPath for SVDE that need to be reflected in the context provided back in DAVE. https://docs.google.com/spreadsheets/d/1rPvEoP9iYNkxJ0eWC8gXe3ci7e6mhW0da59xkGhadi0/edit#gid=502967565
