### ISSUE TITLE
Failure to process query with stop words

### ISSUE THREAD

**Issue by elrayle** [LD4P/qa_server#94]
## Description

When a stop word is included in the pref label and used in a search, the cache system fails to find a match.

## Expected

curl -L -D - -H 'Accept: application/n-triples' 'http://services.ld4l.org/ld4l_services/loc_performance_batch.jsp?query=spoils%20of%20war&maxRecords=20&lang=en'

to return a single match with URI: `http://id.loc.gov/authorities/performanceMediums/mp2016015015`

The cache indexing system should ignore stop words when included in the query.

## Actual

curl -L -D - -H 'Accept: application/n-triples' 'http://services.ld4l.org/ld4l_services/loc_performance_batch.jsp?query=spoils%20of%20war&maxRecords=20&lang=en'

returns 0 matches

curl -L -D - -H 'Accept: application/n-triples' 'http://services.ld4l.org/ld4l_services/loc_performance_batch.jsp?query=spoils%20war&maxRecords=20&lang=en'

returns 1 matches with URI: `http://id.loc.gov/authorities/performanceMediums/mp2016015015`

NOTE: The only difference is the second query does not include the stop word `of`.  That is, the failing query is `spoils of war` and the successful query is `spoils war`.

## Related Work

#13 Request authority LCMPT be supported

**Comment by eichmann** [comment]
Filtering of stop words in conjunctive query processing now in place.

**Comment by elrayle** [comment]
Closing:  @eichmann put stop work support into the cache system.
